### ISSUE TITLE
Info Link Open a empty tab in Browser 

### ISSUE THREAD

**Issue by ghost** [mongodb-js/compass#1876]
In Latest update of mongo compass info link open a new Empty tab in browser

**Comment by durran** [comment]
Could you please specify which info link you are referring to?

**Comment by veerarajkumar** [comment]
Even all link will be open as empty tab in browser..

**Comment by durran** [comment]
Could you please provide?

1. Compass version
2. OS
3. A screenshot showing the link or links you are clicking

I am cliking on our info links in the latest Compass (1.20.4) in various locations and they all work for me, so it would be helpful to see exactly what you are trying to do. Thanks!

**Comment by Anemy** [comment]
Going to close this for now, feel free to reopen if anyone experiences this or if you've got more information we can use.
