### ISSUE TITLE
The explain plan result page element dislocation

### ISSUE THREAD

**Issue by zicokuo** [mongodb-js/compass#1883]
When I perform query analysis on a sharded cluster MongoDB ,
Elements of analysis results are misplaced.
The reason is that the parent element wrapping `div.ExplainPlanPlugin_explain-tree-explain-tree` is missing css `{ display: flex ; justify-content: center }`;

![image](https://user-images.githubusercontent.com/4969958/72117255-0030fa00-3388-11ea-8600-f43eee886739.png)

**Comment by lrlna** [comment]
thanks for reporting this.

tracking jira issue: https://jira.mongodb.org/browse/COMPASS-4093

**Comment by lrlna** [comment]
hey @zicokuo! This should be fixed in our latest stable `1.20.5`. Try it out and see if it works for you.

**Comment by Anemy** [comment]
Closing - if this issue persists feel free to reopen :) Thanks again for reporting.
