### ISSUE TITLE
String property rendered with additional space at end

### ISSUE THREAD

**Issue by IrishAdo** [mongodb-js/compass#1889]
Using a Mac with all the latest updates ( os 10.15.2) Mongo Compass Community (Version 1.19.12 (1.19.12))

I have a document  that looks something like

`{ level1 : "A String"}`

when I open the document in mongoDB compass community it is rendered (LIST VIEW) with an additional space at the end of all strings 

`{ level1 : "A String "}`

**Comment by lrlna** [comment]
hey @IrishAdo! I am trying this out on our latest stable (1.20.5), and I am not able to see this in nested documents. For example: 
![Capture d’écran, le 2020-02-12 à 13 56 31](https://user-images.githubusercontent.com/8107784/74336950-a749ec80-4d9f-11ea-9409-8d55e781bebc.png)

Would you mind updating to the latest stable and seeing if the problem goes away for you?

**Comment by IrishAdo** [comment]
Will check tomorrow when I’m in the office

**Comment by IrishAdo** [comment]
Sorry it took so long I can confirm that this is working as expected

**Comment by lrlna** [comment]
Sweet! Glad it's working out
