### ISSUE TITLE
Documents and Aggregations tabs do not work correctly when connected to mongodb collection that have huge documents

### ISSUE THREAD

**Issue by jchobantonov** [mongodb-js/compass#1894]
## Feature Request
When I try to connect to mongodb server that have 14MB for each document (like a document that have one binary field) in the collection (around 10 documents is enough to trigger this behavior) the hosted mongodb atlas in *.mongodb.net will report error as matched documents exceed 100MB and they do not fit into the RAM - even if the client passes allowDiskUse:true the hosted server will ignore this.
When this happens Documents tab on it's initial load will show there is no documents and on the bottom it will popup line bar saying loading error from server (I need to then use projection to exclude the document field that is the huge binary data in order to load the set)
As this is fine - e.g. I could alter the query to not load more stuff into the result set it would be beneficial to try to load documents by using id only projection at least to see some documents and have some warning that a projection was used as having No Documents seems like the collection is empty if no one pay attention to the warning loading error that disappear after some time

As for Aggregate tab - this is where it is not usable as the tab will not render any content into itself - e.g. it will be empty so a client of mongodb UI can't use this tab at all - I can't change the filter/aggregate etc
 
## Detailed Description
At least fix Aggregate tab to work - e.g. to be able to add aggregation and test it out

## Context
Have ability to use aggregations even if the documents in mongodb are huge

I'm using Windows version of MongoDB Compass Comunity UI version 1.20.3

## Possible Implementation
>

**Comment by lrlna** [comment]
Hey @jchobantonov! Thanks so much for reporting this. I've created a [jira ticket](https://jira.mongodb.org/browse/COMPASS-4141) for us to track for a possible solution.

**Comment by Anemy** [comment]
Hi @jchobantonov we've been looking into this a bit. I think these features are currently working as expected. It looks like even when we have documents with binary data fields that are > 5mb we're able to load the crud UI and aggregations ui and still perform actions. We are looking into improving that error message you've mentioned to make it a bit more descriptive and visible. Going to close this, feel free to reopen. Thanks for reporting!
