### ISSUE TITLE
Requery when "Find" is pressed, regardless whether the search filter has changed

### ISSUE THREAD

**Issue by claytongulick** [mongodb-js/compass#1897]
Currently, if you perform a search on a collection, if you press "Find" again the search won't be performed again unless the query has changed.

This doesn't work well when an external system has changed the data and you want to repeatedly query the collection to check for the changes.

When pressing "Find" regardless of whether the search has changed since the last query, a new search should be performed.

Thanks!!

**Comment by lrlna** [comment]
Hey @claytongulick! Your use case makes a lot of sense. I've made an [issue on our jira](https://jira.mongodb.org/browse/COMPASS-4140) to track this there.

**Comment by Anemy** [comment]
Hey @claytongulick we've just released version [1.26.0](https://github.com/mongodb-js/compass/releases/tag/v1.26.0) which has a fix for this. Thanks for bringing this up! Feel free to reopen if you find it's not working quite right.

**Comment by claytongulick** [comment]
Thanks!!!
