### ISSUE TITLE
Enabling mongodb-js/compass to be web-broswer based and accessible via a link

### ISSUE THREAD

**Issue by kwill4026** [mongodb-js/compass#1903]
I would like the mongodb-js/compass to work in a way in which one can visit a link (http://127.0.0.1:27017) in their web browser to access Compass. When the user pulls down the Github they would simply  git clone the project, install dependencies with npm install, start the app with npm start and then visit http://127.0.0.1:27017 in their browser. My usage is for when I dockerize  mongodb-js /compass, an run  the container it would be listening on http://127.0.0.1:27017 in which I could expose it with a node port for a user to access via their web-browser.

**Comment by lrlna** [comment]
hey @kwill4026! This is currently not possible and there are no plans in the near future to make compass work in the browser. It only works in a desktop environment. If you'd like, you can submit a feature request to [our feedback forum](https://feedback.mongodb.com/forums/924283-compass) so we can track how many folks want this feature a bit more.

**Comment by kwill4026** [comment]
@Irlna thanks for the quick response. I may look through the source code briefly and see if its possible to expose it to be browser based. If I dont see anything I will not worry about it.
Thanks.

**Comment by wildone** [comment]
would be great to be able to run inside a docker stack :D will save a lot of holes in the stack :D
