### ISSUE TITLE
A JavaScript error occured in the main process

### ISSUE THREAD

**Issue by wulfnb** [mongodb-js/compass#1926]
If MongoDB is in idle for some time i'm getting the error popup with an Ok button.

**A JavaScript error occured in the main process**

If we press ok then application exiting.

Screenshot attached
![Screenshot from 2020-03-20 17-09-23](https://user-images.githubusercontent.com/46603705/77161045-b3c41200-6ace-11ea-843c-e682fc13ad20.png)

**Comment by imlucas** [comment]
@wulfnb which version of compass are you running? This bug was fixed in 1.16.1 https://jira.mongodb.org/browse/COMPASS-3156 If you update to a newer version, you should not see this message any longer.

**Comment by wulfnb** [comment]
I'm using version 1.15.1

**Comment by imlucas** [comment]
@wulfnb great then updating to a new version will fix this problem eg https://github.com/mongodb-js/compass/releases/tag/v1.20.5
