### ISSUE TITLE
Disable a plugin

### ISSUE THREAD

**Issue by yelled3** [mongodb-js/compass#1929]
Is there a way to disable a plugin in Compass?

I see in the `Installed Plugins` window a list of all the plugins, with little check marks next to each.
but no way to disable any of them.

I couldn't find anything in the official docs...

> Why do I want to disable a plugin?
when working against a remote DB, the `Collection Stats` plugin really slows me down. (tabs take a few seconds to load since it does a count query on the collection)

Thanks :-)

**Comment by Anemy** [comment]
Hi @yelled3 - currently there's no way to disable plugins in Compass. 
It is a feature request though, so maybe we can get around to it soon.
If it's alright I'll close this issue and we can use this feature request in our feedback forum (which allows for voting): https://feedback.mongodb.com/forums/924283-compass/suggestions/40564801-ability-to-disable-plugins

I think the main issue here though is that the `Collection Stats` is running a full count. We could be using the estimated count in this instance, skip the count, or perform the count in the background which would make it to you're not slowed down. That's something we are planning on working on sooner.
