### ISSUE TITLE
Exporting sorted data doesn't work

### ISSUE THREAD

**Issue by chaizeg** [mongodb-js/compass#1931]
Hello,

I'm currently using MongoDB Compass (version 1.20.5) for work on Windows 10. When I launch find with 'sort' and 'filter', the result i get in the GUI is correct, but once I try to export the data with that same query it doesn't work at all. I tested  for 'sort' alone, it didn't work too, but for 'filter' alone It worked.

Is this an issue in Compass or is there a way for me to fix it?

Thank you!

**Comment by Anikei** [comment]
**Build Info:**
MongoDB Compass 1.20.5
Windows 10

It looks like query works only for "filter" options only, any other options and combinations are ignored, even "filter + limit" (limit is skipped).

There is also no signs of "Filter" aggregation definition in query input on Export Collection popup window. Only inner JSON is displayed and it looks like input designed for the single type of aggregation.

**Comment by tkeidar** [comment]
any update on this issue?

**Comment by alenakhineika** [comment]
Hey, thank you for opening the issue! In the upcoming import/export redesign we are going to solve this problem.

**Comment by Anemy** [comment]
It's being tracked in https://jira.mongodb.org/browse/COMPASS-5576 - if folks would like alerts for when that's done you can add yourself as a watcher for updates. Once that's done I think the import/export flow should make a lot more sense for folks, and I'm thinking we can close ticket then.

**Comment by Anemy** [comment]
The newly released Compass `1.37.0` with the new import and export flow makes this a thing of the past! You can now include a sort in your query and it'll be used when exporting results.
You can find it here: https://github.com/mongodb-js/compass/releases
Thanks again for opening up the issue.
