### ISSUE TITLE
x509 authentication does not work

### ISSUE THREAD

**Issue by jeffrson** [mongodb-js/compass#1932]
While I can choose x509 authentication for a new mongodb connection it's obviously non functional.

It asks for a "username" while it should offer to load the certificate and key.

I tried to paste the filename but to no avail. The username (DN) does not (and cannot) work either.

**Comment by Anemy** [comment]
Hi @jeffrson
To use x509 with Compass the certificate and key are inputted in the `SSL` section in the `More options` tab.
Here's a screenshot of that page with an x509 connection I'm using (NOTE: the Certificate Authority isn't used and can be anything)
<img width="618" alt="Screen Shot 2020-09-23 at 6 30 31 PM" src="https://user-images.githubusercontent.com/1791149/94041685-df4fee00-fdca-11ea-9655-d5dd74cb58da.png">

I also ran into the UX problem you're running into the other day (and found it frustrating as well :) ), I created this ticket: https://jira.mongodb.org/browse/COMPASS-4402 which hopefully will help cases like yours going forward.

Also - sorry for the late reply - we've now started to look at github issues more in depth, most of our issues come through jira. Closing this, feel free to reopen if something is up.

**Comment by Anemy** [comment]
Also from the [compass connecting docs](https://docs.mongodb.com/compass/current/connect/):
___
If you are using [Atlas-managed certificates](http://docs.atlas.mongodb.com/security-add-mongodb-users/#select-an-authentication-method), your username must be prefaced by “CN=” per[ RFC 2253](https://tools.ietf.org/html/rfc2253.html). For example, the username “X509User” must be provided as “CN=X509User”.
