### ISSUE TITLE
Feature Request: Pre-populate collection name while exporting a collection

### ISSUE THREAD

**Issue by thesanjeevsharma** [mongodb-js/compass#1934]
## Feature Request
Pre-populate collection name while exporting a collection

## Detailed Description
When I am exporting a collection, a dialog appears asking for the location and file name. The file name field is blank by default.

## Context
So according to UX, it's better to have the collection name written there already. Users can edit it if they want to use something else. Recently, I had to export nearly 10 collections and had to write the same names for them every time.

## Possible Implementation
We can pass the collection name to the dialog so it pre-populates it. I would like to work on this if you allow me to. :)

**Comment by Anemy** [comment]
@thesanjeevsharma Opened a pr for this https://github.com/mongodb-js/compass-import-export/pull/211 - if it makes it in it'll be in a future release of compass.
And just saw you mentioned you'd be up for working on it sorry 😅 
Thanks for the good suggestion.
