### ISSUE TITLE
Make left aggregation column resizable

### ISSUE THREAD

**Issue by zbayoff** [mongodb-js/compass#1935]
## Feature Request
Allow the left aggregation column to be resizable.

## Detailed Description
On the Aggregations Tab, the left column width is always fixed. Can this be made to be resizeable?

![mongodb](https://user-images.githubusercontent.com/30878344/79046352-6ffc8e00-7bde-11ea-9098-38b129bc4d85.png)

## Context
 Many times aggregation configs get quite complex and long and it is painful to keep horizontally scrolling to see the nested configs.

**Comment by Anemy** [comment]
Hi Zach - thanks for the good suggestion. I think this is definitely something we can improve.
We take a lot of input from our feedback forum as well. Here's the issue there if you'd like to upvote for visibility: https://feedback.mongodb.com/forums/924283-compass/suggestions/40319923-resize-input-field-within-aggregation-editor

**Comment by Anemy** [comment]
Resizable aggregation editors added in 1.26
