### ISSUE TITLE
Timeout error on incorrect case in username

### ISSUE THREAD

**Issue by charsi** [mongodb-js/compass#1950]
Just spent 30 minutes trying to troubleshoot this. 

It seems usernames for mongo db can be case sensitive (which itself was a surprise to me). If a user tries to connect with the correct username but with some letters in the wrong case (MYuSer instead of MYuser) then compass shows a timeout error.

![image](https://user-images.githubusercontent.com/826310/80765144-26290880-8af7-11ea-8015-c3527b725220.png)

Expected behavior would be either the user is allowed to connect if case sensitivity shouldn't exist in user names. Or display a more accurate error message.

**Comment by Anemy** [comment]
I think this works as intended with MongoDB. Probably best to create a ticket with MongoDB if you would expect case insensitivity. Also nice name if that's from diablo 2!
