### ISSUE TITLE
linux not saving favorites

### ISSUE THREAD

**Issue by nautilor** [mongodb-js/compass#1956]
I'm currently experiencing a problem,
Under linux when I save a connection to my favetorites and then close and repoen the program
the connection saved is gone
by running mongodb-compass from console i saw this error

`(node:25335) UnhandledPromiseRejectionWarning: ReferenceError: error is not defined
    at /usr/share/mongodb-compass/resources/app.asar/node_modules/storage-mixin/lib/backends/secure-main.js:87:42
(node:25335) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)`

mongodb-compass version: 1.20.5

UPDATE

I've updated to version 1.21 but the problem is still there

**Comment by Anemy** [comment]
At first glance this is an issue with how our credential store is being used in linux. Does your linux have a credential store installed, like https://wiki.gnome.org/action/show/Projects/GnomeKeyring?action=show&redirect=GnomeKeyring ?

**Comment by Anemy** [comment]
Since we've got two of these I'm closing this as a duplicate. Here's an earlier issue we can use: https://github.com/mongodb-js/compass/issues/1911
