### ISSUE TITLE
Bug Report: document count not updated on "Refresh"

### ISSUE THREAD

**Issue by bluepuma77** [mongodb-js/compass#1977]
## Feature Request
Document count is currently not re-freshed when pressing "REFRESH". Instead I need to close the Documents tab and re-open it to see the current Document count.

## Detailed Description
See above, "Refresh" should "refresh" the whole view.

## Context
I like to see if I create or delete objects in the background. Always closing and re-opening the tab is not a nice user experience.

## Possible Implementation
Just refresh the Document count along the displayed data.
<img width="773" alt="Mongo-count" src="https://user-images.githubusercontent.com/5221187/85805182-e9227080-b74b-11ea-9d0d-519790e59d76.png">

**Comment by kevin-mitchell** [comment]
This caught me up as well today. 👍

**Comment by alenakhineika** [comment]
The issue is fixed. Feel free to re-open if you encounter the problem again.
