### ISSUE TITLE
Question: Run aggregations within MongoDB Compass

### ISSUE THREAD

**Issue by dakshshah96** [mongodb-js/compass#1988]
## Question

Is there a way to execute the aggregation I've built and get the results in Compass?

## Additional context

The aggregation builder is a great feature to have and brings Compass at par with famous softwares like [Studio 3T](https://studio3t.com/). There is however, no way to actually execute the aggregation I've built inside Compass or at least have a shell where we can type commands. Even the [docs](https://docs.mongodb.com/compass/master/aggregation-pipeline-builder/#execute-the-pipeline) suggest running them using `mongod`.

With the already fantastic support for auto-completion and aggregation pipeline builder, it'd be great to have the ability to actually execute aggregations inside Compass. And now that Compass is open source, it's great that the MongoDB community doesn't have to resort to expensive tools like Studio 3T for interacting with their database on a daily basis. Looking forward to see Compass catch up with [Studio 3T features](https://studio3t.com/features/) soon!

**Comment by Anemy** [comment]
Hi @dakshshah96 - In our next release coming in the next few weeks we'll have be adding an embedded shell in compass. It'll be able to run aggregations and show results.
