### ISSUE TITLE
Adding new collection name with dot at the end creates new collection.

### ISSUE THREAD

**Issue by szygendaborys** [mongodb-js/compass#1992]
Creating a new collection with the dot (".") at the end of the collection name returns an error, but also creates a collection with the dot included. Additionally, you can neither remove or enter into this collection.

#### Current Behavior

I have clicked a "+" in Mongo Compass in order to create a collection named "absences". By mistake I wrote  "absences." and clicked "Create". An error was returned, but collection has been created anyway.

#### Expected Behavior/Code

Application should not create wrongly spelled collection.

#### Environment

- node.js / npm versions: 
- OS: Windows 10
- MongoCompass version: 1.21.2

#### Possible Solution

Check error handling.

**Comment by Anemy** [comment]
Hi @szygendaborys - thanks for reporting, and sorry for the late reply on this. If you update to the [newest version of Compass](https://github.com/mongodb-js/compass/releases) (1.29.5 at the time of writing) this issue has been fixed. Thanks for using Compass and helping improve it!
