### ISSUE TITLE
Dots in key names cause error

### ISSUE THREAD

**Issue by damiantoczek** [mongodb-js/compass#1999]
When creating an object, via compass it's not possible to create keys that use dots.
Here a example: `usb-c 3.1` causes an error, when the dot is removed, it works.

The unlogic things happens now. I can edit/update it and add the dot afterwards and it won't show any errors, I hope this is just a bug and not intended to be.

**Comment by Anemy** [comment]
Which version of MongoDB are you running? Dot in a key name was added in 3.6: https://docs.mongodb.com/manual/core/document/#field-names

It also has a bit of a warning around its usage:
```
The MongoDB Query Language cannot always meaningfully express queries over documents whose field names contain these characters (see SERVER-30575).

Until support is added in the query language, the use of $ and . in field names is not recommended and is not supported by the official MongoDB drivers.
```

**Comment by Anemy** [comment]
<img width="606" alt="Screen Shot 2020-09-23 at 11 28 53 AM" src="https://user-images.githubusercontent.com/1791149/93994246-f8877900-fd8f-11ea-8c7e-a5c9ece09685.png">
Ah looks like our document creator is doing some validation which is too strict for this case (it was built around the time of 3.6). Looks like something we can improve. Thanks for bringing it up

**Comment by Anemy** [comment]
Sorry - spoke a bit too soon, this error is from the [mongodb node driver](https://github.com/mongodb/node-mongodb-native). The driver currently doesn't support dots in key names. 
```"Until support is added in the query language, the use of $ and . in field names is not recommended and is not supported by the official MongoDB drivers."```

Maybe once this ticket: https://jira.mongodb.org/browse/SERVER-30575 is worked on we'll have support. Closing till then if that's alright.
I don't think there's a good work around I can suggest :/
