### ISSUE TITLE
Feature Request: Can you please move the new tab button next to the last tab.

### ISSUE THREAD

**Issue by saisandeepvaddi** [mongodb-js/compass#2017]
## Feature Request
New Tab button seems too far to reach and easy to miss.

Almost every application with tabs seems to have the new tab button right next to the last tab.(Chrome, Firefox etc.,)

## Context

Although this doesn't have to do with actual functionality I personally keep missing the tab button. I'm no UX expert but it seems keeping it right next to the last tab feels familiar and easier.

## Possible Implementation

![image](https://user-images.githubusercontent.com/13838175/93914992-5d31cd80-fcd5-11ea-8c83-4f34206cdf4a.png)

Please consider making it Chrome-like tabs.

**Comment by saisandeepvaddi** [comment]
I just saw the compass-screenshot in the repo. It already seems to have it like that.

Is that part of a new release?

**Comment by Anemy** [comment]
Good suggestion - here's a PR: https://github.com/mongodb-js/compass-collection/pull/129
Once that's merged in, it'll be in one of the next Compass releases.

**Comment by saisandeepvaddi** [comment]
Awesome. Looking forward to the release 👍

**Comment by Anemy** [comment]
@saisandeepvaddi  Fix is live in the new version 1.23.0 ! Thanks again. Feel free to open if still happening with the new version.

**Comment by saisandeepvaddi** [comment]
Thank you :)
