### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by bigshans** [mongodb-js/compass#2028]
#### Current Behavior

When I input, the cursor position is always a few characters away from the position I am editing.

#### Code/Gist

Any Input text aera you can try, I have always been like this.

#### Expected Behavior/Code

The cursor position is on my edit position

#### Environment

- node.js / npm versions: v14.12.0/6.14.7
- OS: 5.8.11-1-MANJARO

**Comment by addaleax** [comment]
Could you maybe share a screenshot, or screencapture, demonstrating the problem?

**Comment by bigshans** [comment]
@addaleax Here is a screenshot:
![Peek 2020-10-06 18-51](https://user-images.githubusercontent.com/26884666/95192699-285d6480-0805-11eb-8526-0cb004de60f5.gif)

**Comment by addaleax** [comment]
Thanks, I’ve opened https://jira.mongodb.org/browse/COMPASS-4436 to track this on our side

**Comment by addaleax** [comment]
We probably won’t get around to fixing this because this looks like a OS-specific font issue, which may not be under our control. Thank you for reporting this, though!
