### ISSUE TITLE
Bug Report: table header overlapped when viewing object fields

### ISSUE THREAD

**Issue by xoox** [mongodb-js/compass#2040]
#### Current Behavior

When viewing document with object fields as the following example in table view, table headers overlapped and not properly aligned with table cells.

 ```json

{
    "_id": {
        "$oid": "5f8e8fae2926d90429ceeddc"
    },
    "assets": {
        "id": "llll",
        "race": "mmm"
    }
}
```

#### How to re-produce

1. Create a new empty collation and a document with the above example.
1. Check collections in table view.
1. Click the expansion button in assets field to open a tab of this object.

The first two headers of table view will overlap each other. See the attached screenshots.

#### Expected Behavior/Code

When viewing the field of object type, there's no overlap in the table header.

#### Environment

- compass: 1.23.0-beta.3
- OS: Windows 10 2004
- Browser: Edge 86

#### Additional Context/Screenshots

![image](https://user-images.githubusercontent.com/1014277/96695829-afd9d480-13bc-11eb-9f29-174dd3028903.png)
![image](https://user-images.githubusercontent.com/1014277/96696116-fcbdab00-13bc-11eb-841f-4a30fae7d9a7.png)

**Comment by Anemy** [comment]
Hi @xoox - thanks for opening the ticket - we've just fixed this in our data explorer: https://github.com/mongodb-js/compass-crud/pull/291
It'll be in the next release :D
I'll leave this ticket open until it's released and then we can close it.

**Comment by Anemy** [comment]
It's live! Thanks again. Feel free to open if still happening with the new version.
