### ISSUE TITLE
Feature Request - Allow to set an alias to a given connection

### ISSUE THREAD

**Issue by gabrielfbarros** [mongodb-js/compass#2041]
## Detailed Description

It would be great if we could set an alias to an given connection on Compass. When you have several connections to different servers, you need to memorize what each ip address stands for.

**Comment by Anemy** [comment]
Hi @gabrielfbarros Compass has the ability to save connections as favorites which, as I understand it, does what you want! :D
Here's the docs page on it: https://docs.mongodb.com/compass/master/connect/favorite-connections

**Comment by gabrielfbarros** [comment]
@Anemy yes, that's what I was looking for. Thanks!

I'm wondering if in future versions of Compass, those options could be easier to find, because I would never find those, I mean, it's not intuitive. But, now I already know, thanks again!
