### ISSUE TITLE
Bug Report with solution - Loading page stuck

### ISSUE THREAD

**Issue by Utsav-Ladani** [mongodb-js/compass#2061]
# Loading page stuck

#### Current Behavior

When install mongoDB compass in windows OS it not start properly. Loading page stuck and error message throw in dev console

I read about it on jira,mongodb.org and only few people get this error.

#### Expected Behavior

Program should run without error

#### Environment

- npm versions: not important
- OS: windows 7

#### Possible Solution

Yeah, I solved this issue.

 **Let me tell you why this happen?**

MongoDB compass is made using electron and electron have one dependency with name `windows-release`. All this problem is produced by this dependency.

`windows-release` have two commands to check OS name
1. `wmic os get Caption`
2. `Get-CimInstance -ClassName Win32_OperatingSystem`

When this module try to find os name, it generate error. Because `wmic.exe` file's path not added in `Environment variables` and `Get-CimInstance` is may be old.

**Solution**
I found `Get-CimInstance` command may be old (not sure) so we don't need to do anything with it.
But `wmic` is a executable file in `C:\Windows\System32\wbem`. If we add this file's path in our environment variable, then error will resolve, too simple.

This is not code issue, but i got this issue yesterday, i try to found solution on internet but i can't find anything. So I try myself, follow codebase and finally found this solution.

Say people to do this so they can remove error and use your greate product.
I hope people's problem will resolve.
:+1:

**Comment by Anemy** [comment]
Thanks for reporting this!
Created a ticket to track: https://jira.mongodb.org/browse/COMPASS-4510
I'll post here once we've got an update. 👍

**Comment by Anemy** [comment]
Hi @Utsav-Ladani - we've just released `1.25.0` with a fix for this issue. Going to close this ticket. Feel free to reopen if you upgrade and it still persists. Thanks again for reporting it!
