### ISSUE TITLE
Will there be support for macOS/AArch64?

### ISSUE THREAD

**Issue by jgoldverg** [mongodb-js/compass#2068]
## Question
Hi all I was wondering if there is any intention to have Mongo Compass run natively on macOS/AArch64. 

Currently I have gotten it running using Rosetta 2, but this has obvious flaws(huge battery consumption to start with). It would be really awesome if there could support for the new m1 Macs. 
## Additional context
I am not sure what work this would take, but if there is anything you need to provide or do please let me know. If there could be an issue tracker for this that would be great!
Thanks

**Comment by LinusU** [comment]
Electron is currently fixed at version `6.1.7`, we need to get to at least `11.0.0` for arm64 support.

https://github.com/mongodb-js/compass/blob/2deb992ea07d303e14752f79dd4653b4a717fa17/package.json#L387

Trying to upgrade it I ran into issues with it being stuck at 6.x in hadron-build: https://github.com/mongodb-js/hadron-build/issues/430

**Comment by jgoldverg** [comment]
Was just looking into the current [electron](https://github.com/electron/electron/releases/tag/v12.0.5) version, seems they are v12.0.5. Any chance that you could try again @LinusU?

**Comment by ngohungphuc** [comment]
I'm still waiting for m1 version :(

**Comment by LinusU** [comment]
@Anemy I believe that this issue is asking for _native_ M1 support, it seems like `darwin-x64` packages attached to the linked release?

If you're on a recent version of Electron, it should be easy to do that as well. I'm not familiar with the Hadron build tools, but in e.g. electron-packages and Electron Forge you can pass in `--arch=arm64` when you build.

**Comment by AbdullahDiaa** [comment]
Yep, it seems there's only `darwin-x64` packages attached to the release.
the application uses rosetta 2 translation layer on M1 macs.
![Screen Shot 2022-03-04 at 12 06 50 AM](https://user-images.githubusercontent.com/733794/156652995-8b3553c3-2ad9-4078-87cd-fe757fda11bc.png)

**Comment by petrhaus** [comment]
2 months later, and with the jira ticket unassigned, I'd like to ask if "soon" is really going to happen any soon :-)

**Comment by dungmv** [comment]
2 years

**Comment by lockieluke** [comment]
as far as i know compass is already on electron v13 theres no way they cant support apple silicon

**Comment by RodrigoRosmaninho** [comment]
I've taken the current master branch (as of this reply) and compiled it on an Apple Silicon machine.
Everything seems perfectly functional, and Activity Manager now shows "Kind: Apple" for all the MongoDB Compass processes 🙂

You can get the dmg file I generated on this link and try it for yourself while you wait for an official release: [https://drive.google.com/file/d/1Gzx1YXxv2ZimEZ6wFUEx94h4HGYNJkaw/view?usp=sharing](https://drive.google.com/file/d/1Gzx1YXxv2ZimEZ6wFUEx94h4HGYNJkaw/view?usp=sharing)

After dragging the app to the Applications folder you'll need to run this:
`xattr -d com.apple.quarantine /Applications/MongoDB\ Compass\ Dev.app`

Because Apple places App files downloaded from the internet (from unknown developers/sources) in quarantine and reports them as "damaged" to the user.

**Comment by neumann-nico** [comment]
@RodrigoRosmaninho Thank you very much! Which steps did you do to compile it?

**Comment by dungmv** [comment]
> I've taken the current master branch (as of this reply) and compiled it on an Apple Silicon machine. Everything seems perfectly functional, and Activity Manager now shows "Kind: Apple" for all the MongoDB Compass processes 🙂
> 
> You can get the dmg file I generated on this link and try it for yourself while you wait for an official release: https://drive.google.com/file/d/1Gzx1YXxv2ZimEZ6wFUEx94h4HGYNJkaw/view?usp=sharing
> 
> After dragging the app to the Applications folder you'll need to run this: `xattr -d com.apple.quarantine /Applications/MongoDB\ Compass\ Dev.app`
> 
> Because Apple places App files downloaded from the internet (from unknown developers/sources) in quarantine and reports them as "damaged" to the user.

You are my hero :D

**Comment by RodrigoRosmaninho** [comment]
> @RodrigoRosmaninho Thank you very much! Which steps did you do to compile it?

@neumann-nico here are the steps I went through:

1. Clone the repo
2. Bump node version to one that supports Apple Silicon in both package.json and packages/compass/package.json (I used 16.16.0)
3. Bump electron-packager to version 15.5.1 in packages/hadron-build/package.json
4. Find and replace all instances of `darwin-x64` to `darwin-arm64` in packages/hadron-build/lib/target.js 
5. Run `npm install` in the packages/compass directory to download all dependencies
6. Run `sudo npm install -g typescript`
6. Run `tsc` inside the configs/webpack-config-compass directory (If the typescript isn't compiled, compass won't be able to import this module)
6. Run `npm start` in the packages/compass directory to confirm that MongoDB Compass builds and starts successfully
7. Run `npm run package-compass` in the packages/compass directory to create the .App file. In my case this command threw an error at the end, but the .App file had already been successfully created in packages/compass/dist.

**Comment by neumann-nico** [comment]
> > @RodrigoRosmaninho Thank you very much! Which steps did you do to compile it?
> 
> @neumann-nico here are the steps I went through:
> 
>     1. Clone the repo
> 
>     2. Bump node version to one that supports Apple Silicon in package.json, package-lock.json and packages/compass/package.json (I used 16.16.0)
> 
>     3. Bump electron-packager to version 15.5.1 in packages/hadron-build/package.json
> 
>     4. Find and replace all instances of `darwin-x64` to `darwin-arm64` in packages/hadron-build/lib/target.js and packages/hadron-build/commands/release.js
> 
>     5. Run `npm install` in the packages/compass directory to download all dependencies
> 
>     6. Run `npm install -g typescript`
> 
>     7. Run `tsc` inside the configs/webpack-config-compass directory (If the typescript isn't compiled, compass won't be able to import this module)
> 
>     8. Run `npm start` in the packages/compass directory to confirm that MongoDB Compass builds and starts successfully
> 
>     9. Run `npm run package-compass` in the packages/compass directory to create the .App file. In my case this command threw an error at the end, but the .App file had already been successfully created in packages/compass/dist.

Thanks it worked! You should create a pull request :)
Even though there is an error at the end, I think not a lot is missing to be fully working.

**Comment by petrhaus** [comment]
> I've taken the current master branch (as of this reply) and compiled it on an Apple Silicon machine.
> Everything seems perfectly functional, and Activity Manager now shows "Kind: Apple" for all the MongoDB Compass processes 🙂

The performance boost is incredible. Can't wait for the official version.

**Comment by neumann-nico** [comment]
@RodrigoRosmaninho
Things are getting serious: https://github.com/mongodb-js/compass/pull/3269

**Comment by RodrigoRosmaninho** [comment]
Thanks for the update 👍

**Comment by gribnoysup** [comment]
arm64 build for macOS is now available in the [download center](https://www.mongodb.com/try/download/compass) for the latest beta (1.33.0-beta.2) and will be available in the next stable release so I'm closing the issue. If something in the beta doesn't work for you, please feel free to open a new issue with a specific issue details

**Comment by AbdullahDiaa** [comment]
For some reason the arm64 download link is not listed, just replace x64 in the link with arm64 https://downloads.mongodb.com/compass/beta/mongodb-compass-1.33.0-beta.4-darwin-arm64.dmg
