### ISSUE TITLE
Feature Request: allow the left panel with the database names and collections to resize

### ISSUE THREAD

**Issue by RohanTalip** [mongodb-js/compass#2096]
## Feature Request

The left panel with the database names and collections can be expanded (and collapsed), but only to a pre-determined width.  It can't currently be resized and I'm looking at some quite long database and collection names, so it would be great if it could be resized.

## Possible Implementation

Having a draggable handle for the divider would be ideal.

**Comment by Anemy** [comment]
Hi @RohanTalip In the recent release https://github.com/mongodb-js/compass/releases/tag/v1.29.4 `1.29.4` we've added the ability to resize the sidebar by dragging.

Thanks for opening the issue! Feel free to reopen if you update and it doesn't work as expected.
