### ISSUE TITLE
Feature Request: Be able to search databases and collections independently 

### ISSUE THREAD

**Issue by RohanTalip** [mongodb-js/compass#2097]
## Detailed Description

I'm using MongoDB Compass with a lot of databases, each of which have many similarly named collections.

The search bar currently filters both database names **and** collection names at the same time, but if I'm searching for a database name with a string that also appears in a collection name that appears in most databases, the database that I'm really looking for is lost among all the results that include the databases that have matching collections.

## Possible Implementation

I suggest splitting the search field into 2, one field for the database names and one for the collection names.  If necessary, maybe add a toggle for the "advanced" search.

**Comment by Anemy** [comment]
Created a ticket to track this: https://jira.mongodb.org/browse/COMPASS-5499
We might not expose this functionality in the sidebar panel for the sake of visual space, but it definitely does make sense for folks to be able to independently text search collections and databases, it just may be on the databases and collections views.
Thanks for bringing this up! (And sorry for the late response).
