### ISSUE TITLE
When trying to build Compass it fails when running `transformPackageJson`

### ISSUE THREAD

**Issue by dutzi** [mongodb-js/compass#2098]
When trying to build Compass locally, by running:

```
npm run release-evergreen
```

I get the following error message:

```
Packaging app for platform darwin x64 using electron v6.1.7
Downloading patent safe FFMPEG for platform darwin x64 using electron v6.1.7
Loaded FFMPEG successfully
✖  Error: TypeError: Cannot set property 'productName' of undefined
    at transformPackageJson (/Users/dutzi/projects/compass/node_modules/hadron-build/commands/release.js:335:52)
```

Seems like it's not reading `package.json`.

I hope I'm approaching this correctly, as this is pretty new to me. What I'm trying to achieve is to have `./dist` populated with a .dmg file I can run.

**Comment by addaleax** [comment]
Can you run `export HADRON_PRODUCT='mongodb-compass' HADRON_PRODUCT_NAME='MongoDB Compass' HADRON_DISTRIBUTION=compass` in the shell before you build locally?

**Comment by dutzi** [comment]
That did the trick. Thanks!

I'm going to abuse this thread, I it's ok, with a follow up question. 

I'm seeing my changes working when running `npm start`, however after running:

```
HADRON_PRODUCT='mongodb-compass' HADRON_PRODUCT_NAME='MongoDB Compass' HADRON_DISTRIBUTION=compass npm run release-evergreen
```

And installing the new .dmg file, those changes are gone.

Is there a build step I'm missing?

Note that those changes I'm making are made in `@mongodb-js/compass-query-bar`, which is build locally (by running `yarn start:watch`) and 

Thanks again!

**Comment by Anemy** [comment]
@dutzi We've recently updated the way Compass is built and run locally (moved a number of the packages & plugins into this repo), now the changes that happen in this repo should be easier to deploy and build. If it's alright I'm going to close this issue - feel free to reopen!

**Comment by dutzi** [comment]
That's great! I'll give it a try, thanks.
