### ISSUE TITLE
Compass fails to filter documents when filtering using an int64 value

### ISSUE THREAD

**Issue by Astronought** [mongodb-js/compass#2102]
I'm running MongoDB Server 4.4, using the latest version of Compass and I'm experiencing a weird issue when attempting to query documents using Compass.

My documents contain a field that is an int64, I'm using the latest C# driver to persist the data to MongoDB, documents are inserted/updated completely fine when querying this field from C#.

However when I attempt something like the following in Compass it fails to filter the results: { SomeField: NumberLong("12345678910111213") }. 

The same query works as expected when executed inside the Mongo shell, and as stated before works perfectly fine when queried from C# as well.

**Comment by Anemy** [comment]
Hi @Astronought we've included a fix for this issue in the most recent release `1.31.2`
![Screen Shot 2022-04-15 at 5 42 27 PM](https://user-images.githubusercontent.com/1791149/163635462-2080c4e2-9d0c-4ec7-a7bc-6304638f07b2.png)

It's available for download here:
https://www.mongodb.com/try/download/compass
https://github.com/mongodb-js/compass/releases
Going to close this, feel free to reopen if the issue persists. Thanks for reporting this and helping improve Compass!
