### ISSUE TITLE
Feature Request: add server version to access UI through URL?

### ISSUE THREAD

**Issue by tarkh** [mongodb-js/compass#2104]
## Feature Request
Add server version of Compass.

## Detailed Description
At the moment, Compass uses Electron framework to create a desktop application. Are there any plans to make an option where Compass will run as a regular HTTP(S) server with an interface accessible via a URL? I understand that compass is written in Javascript and works via Node.JS and theoretically, such a modification should not be very time-consuming. But the result will be very useful - use compass as a web application without having to run it on a local machine.

Is it worth waiting for such a modification or is it better to consider the option of a separate independent fork?

## Context
Use Compass as a web application without having to run it on a local machine.

## Possible Implementation
If there is a special flag in config - run Compass without use of Electron, only as HTTP(S) server. Optionally - place any application top menu options (if exist) in to the website body.

**Comment by Anemy** [comment]
Hi @tarkh we've got an item in our feedback portal which allows voting on features/ideas: https://feedback.mongodb.com/forums/924283-compass/suggestions/40531942-compass-as-a-webapp
If it's alright I'll close this issue and we can use that to track it. Hopefully we can do this soon, no plans currently though.
