### ISSUE TITLE
Schama analyze do not work as described in documentation with all geoJSON (Polygon example)

### ISSUE THREAD

**Issue by xoac** [mongodb-js/compass#2138]
> In the Schema tab, you can use interactive maps to filter and analyze location data. If your field contains [GeoJSON](https://docs.mongodb.com/manual/reference/geojson/) data or [longitude,latitude] arrays, the Schema tab displays a map containing the points from the field. The data type for location fields is coordinates.

This is quote from: https://docs.mongodb.com/compass/master/schema/#std-label-analyze-location-data 

## Question

Is this documentation problem or compass do not work as expected?

## Additional context

The "analyze" tab in compass work as expected with "Point" but do not with "Polygon". Here is example with screenshots: 

Point:
```
{
    "site": {
        "type": "Point",
        "coordinates": [19, 50]
    }
}
```

![image](https://user-images.githubusercontent.com/1863020/111650326-7a1f0780-8805-11eb-83ec-38e45776ca44.png)

Polygon:
```
{
   "farmid": 1,
    "site": {
        "type": "Polygon",
        "coordinates": [
            [
                [18.998236656188965, 50.000928110654115],
                [19.00098323822022, 50.00139680018827],
                [19.003043174743656, 49.99990800587302],
                [19.002056121826175, 49.998501880019276],
                [18.9979362487793, 49.9992187336323],
                [18.998236656188965, 50.000928110654115]
            ]
        ]
    }
}
```

![image](https://user-images.githubusercontent.com/1863020/111650503-a76bb580-8805-11eb-8064-f6d247d377ea.png)

**Comment by Anemy** [comment]
@xoac Thanks for reporting - we currently don't support this. We'll update the docs to be a bit more descriptive of what we support.
We have a feedback portal that allows for updating features for us to add. If you have a moment, maybe you can upvote this: https://feedback.mongodb.com/forums/924283-compass/suggestions/38666188-display-geojson-types-other-than-points-in-schema
Then we can triage when we can add this feature. Thanks again!

**Comment by hypnoseal** [comment]
It has been a year since this issue was raised. Is there an update regarding progress for Compass support of Polygons or on updating the docs to be clear that this functionality only works with points? Thank you.
