### ISSUE TITLE
Mongosh command keeps on loading

### ISSUE THREAD

**Issue by tbhaxor** [mongodb-js/compass#2155]
#### Current Behavior

Any command I enter in mongosh interface and hit enter, it keeps on loading

#### Code/Gist

Here is very simple example
![image](https://user-images.githubusercontent.com/28386721/113436793-fb2fee80-9402-11eb-8bde-4a8d0a9ed6a5.png)

#### Expected Behavior/Code

It should print the collection name

#### Environment

- node.js / npm versions: v15.11.0
- OS: Manjaro

#### Additional Context/Screenshots

It was working in previous versions, unfortunately couldn't recall which one

**Comment by tbhaxor** [comment]
Any updates

**Comment by addaleax** [comment]
@tbhaxor Which Compass version are you seeing this problem with?

**Comment by tbhaxor** [comment]
@addaleax `1.26.1.beta.7-1` version [here](https://aur.archlinux.org/packages/mongodb-compass-beta-bin/)

I also tried all the packages listed [here](https://aur.archlinux.org/packages/?O=0&SeB=nd&K=mongodb-compass&outdated=&SB=n&SO=a&PP=50&do_Search=Go) and also the git clone. It's not working

**Comment by addaleax** [comment]
@gribnoysup Could this be from the child process failing during startup? I know we talked about something like this, where would the error show up in that case?

**Comment by gribnoysup** [comment]
The symptoms are similar, yeah. We fixed error propagation in https://github.com/mongodb-js/mongosh/pull/721 but I guess latest Compass shipped with a version that doesn't include that. I'll try to set up a VM with Manjaro to investigate

**Comment by gribnoysup** [comment]
Just tried on a fresh Manjaro install and I can't reproduce.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/5036933/114398340-f8ba5b00-9b9f-11eb-8df1-24fb47281548.png">

@tbhaxor anything suspicious you can see in the devtools (you can open them by clicking View -> Toggle DevTools in the menu bar)? If there is nothing suspicious in the output there, there is this very hacky code you can run in the devtools that might help us understand the issue:

```js
// Getting the reference to the runtime from the depths of state
var {childProcess} = global.app.appRegistry.stores['CompassShell.Store'].reduxStore.getState().runtime.runtime;
// Checking the status code of the child process
console.info('Status code', childProcess.exitCode)
// If child exited with non-zero, we spawn sync so we can get an easy access to stderr
if (childProcess.exitCode) {
var {stderr} = require('child_process').spawnSync(childProcess.spawnargs[0], [childProcess.spawnargs[1]], { env: { ...process.env, ELECTRON_RUN_AS_NODE: 1 } })
console.info('stderr:\n')
console.info(stderr.toString())
}
```

Do you mind doing this and posting the output here?

**Comment by tbhaxor** [comment]
@gribnoysup Which AUR repo you have installed?

**Comment by tbhaxor** [comment]
Never mind Its working. I had to delete the profile config from `rm -rf ~/.config/Mongo\ Compass*/`

![image](https://user-images.githubusercontent.com/28386721/114410539-13ed9080-9bc9-11eb-9c8e-0750dac9ec64.png)

**Comment by tbhaxor** [comment]
@gribnoysup @addaleax Are there any plans for Dark Theme?

**Comment by addaleax** [comment]
@tbhaxor https://github.com/mongodb-js/compass/pull/1960 had some initial conversation around this – but yes, this is something that we do want to add at some point. :)

**Comment by jirikrepl** [comment]
@addaleax I would be great to implement dark mode!
