### ISSUE TITLE
Bug Report: explain plan failed on sharded cluster

### ISSUE THREAD

**Issue by artjomkruglenkov** [mongodb-js/compass#2159]
Explain plan does not longer work after upgrading to Compass 1.26.0 

#### Current Behavior

In Compass version 1.26.0 when explain button is clicked in Explain plan section then nothing happens and screen does not update. 

#### Expected Behavior/Code

The expected behavior is to evaluate plan as it was before in version 1.25.0

#### Environment

- node.js / npm versions: v12.16.3 / npm 7.8.0
- OS: OSX 10.15.7

#### Possible Solution

Revert to previous version 1.25.0 where explain plan functionality does work as expected.

**Comment by c4c1us** [comment]
Same issue when using $or operator.

**Comment by Anemy** [comment]
Hi @artjomkruglenkov - thanks for reporting. 
I haven't been able to reproduce this yet, here's couple questions to hopefully help us identify what's happening: 
- Does this happen with every query? 
- How many documents are in the collection? 
- Does it work on a collection with a smaller amount of documents?
- Is this a sharded cluster?

**Comment by artjomkruglenkov** [comment]
Hi @Anemy.

- Does this happen with every query?

Yes, at least with the ones I have tried.

- How many documents are in the collection. 

Around 2.3mil

- Does it work on a collection with a smaller amount of documents?
- Is this a sharded cluster?

Yes, it's a sharded cluster. In fact, after your question I have tried running the same queries with non-sharded mongo setup and much fewer entries. In these cases explain plan works as expected.

**Comment by rose-m** [comment]
Thanks for the response @artjomkruglenkov! I'd have another question that would be interesting: which MongoDB server versions did you connect to? Was the test with the non-sharded setup the same version as the sharded cluster?

Thanks for your help!

**Comment by artjomkruglenkov** [comment]
@rose-m 
The mongodb version is the same for both deployments: 4.2.12.

**Comment by silver-mx** [comment]
I can confirm the same issue, our database is as well mongo db community version 4.2.12. I have tried with mongodb compass 1.26.0 and 1.26.1 and explain shows no results, as it the query were not executed. I needed to downgrade to compas 1.25.0 and explains work fine again.

**Comment by alenakhineika** [comment]
Hey, could you please try this again with the latest Compass? We have a new explain plan experience now, to check if the issue has gone away.

**Comment by himanshusinghs** [comment]
Hi @artjomkruglenkov and @silver-mx! Wanted to check in on how the new explain plan experience is working out for you. Have the recent releases addressed the issue you were facing earlier? Your feedback is invaluable, and we appreciate your insights. 🚀🌟

**Comment by artjomkruglenkov** [comment]
Hi @himanshusinghs. For me, explain plan functionality works as expected in Compass 1.42.0

**Comment by Anemy** [comment]
Sounds good, going to close this then, thanks!
