### ISSUE TITLE
Feature Request - Import/export database - simple backup please!

### ISSUE THREAD

**Issue by mydogspies** [mongodb-js/compass#2160]
## Feature Request

Many of us would like to have a backup/export/import function in Compass like it is in almost any paid or free sql gui. It is literally astonishing that it does not exist for mongodb and must be done manually via command line with all of the errors that may come with that.

## Detailed Description

We already can export a collection but that makes little sense with hundreds or even thousands in one db. We want to be able to export and entire database just like it can be done with ease with mysql/mariadb in for example myphpadmin. Should simply be available on any level up to the entire db in one go.

## Context

It's probably the most basic feature any gui can have. To automate and ease regular maintainance and I am sure  speak for thousand of admins that wander why we still so many years later must pay for Studio 3T when Compass should simply have this. Seem to be obvious to both the MySQL and Postgress community.

## Possible Implementation

Just do it?

**Comment by Anemy** [comment]
Adding some context here, this is a project we're currently planning scoping out. We'll be working on it in the next few months.
To follow along and get updates you can upvote the entry in the feedback forum:
https://feedback.mongodb.com/forums/924283-compass/suggestions/39711439-add-support-to-export-multiple-collections

**Comment by Anemy** [comment]
Going to close this as we're using github issues to track bug reports and the feedback forum to track feature requests and future projects. Thanks for bringing it up!
