### ISSUE TITLE
Unable to use " $accumulator" operator in  "$groupby" stage  in aggregate query 

### ISSUE THREAD

**Issue by khvr000** [mongodb-js/compass#2176]
#### Current Behavior
I wrote a query involving $accumulator and 
ran it in robo 3t as well as Mongo DB Compass

In Robo 3t when I run Query it says that 
"ok" : 0,
	"errmsg" : "unknown group operator '$accumulator'",
	"code" : 15952,
	"codeName" : "Location15952"
![robo3t error](https://user-images.githubusercontent.com/18584104/116617569-9d3beb80-a95b-11eb-934d-35892632603f.png)

Even in Mongo Db Compass 

unknown group operator '$accumulator'
![mongoCompass](https://user-images.githubusercontent.com/18584104/116617827-e7bd6800-a95b-11eb-86b0-42c8a6152806.png)

#### Environment

- node.js / npm versions:
- OS: Linux
- Mongo Db Compass(1.25.0) / Robo 3t(Robo 3T 1.3.1)

#### Possible Solution

Please help me if Im not using latest version of these tools or some other problem

**Comment by addaleax** [comment]
Which mongodb server version are you using? $accumulator is a new feature in 4.4, and the error message is what you would get if you ran it against a server with a lower version.
