### ISSUE TITLE
MongoDB Compass Helper (Renderer) keeps running on quit once connected to a connection

### ISSUE THREAD

**Issue by slackero** [mongodb-js/compass#2215]
## Bug Report
MongoDB Compass doesn't close all processes of `MongoDB Compass Helper (Renderer)` on quit once connected to a connection. 

#### Current Behavior
When MongoDB Compass once was connected to a connection a minimum of one process `MongoDB Compass Helper (Renderer)` stays active in the list of processes on macOS. When MongoDB Compass is just opened and quit without any connection all processes are closed.

#### Expected Behavior/Code
MongoDB Compass should end all processes on quit.

#### Environment
- node.js / npm versions: 14.17.0 / 7.15.0
- OS: macOS 11.4 (20F71)

#### Additional Context/Screenshots

_The list of active processes when MongoDB Compass is open (including mongodb)_
<img width="1280" alt="Bildschirmfoto 2021-05-29 um 09 00 36" src="https://user-images.githubusercontent.com/15139/120059967-29bdf480-c055-11eb-9b7a-8b95c3762751.png">

_The list of processes after quitting MongoDB Compass (including mongodb) and once it was connected_
<img width="1238" alt="Bildschirmfoto 2021-05-29 um 09 01 57" src="https://user-images.githubusercontent.com/15139/120059963-1b6fd880-c055-11eb-914a-6e6fabc8cdbd.png">

**Comment by mcasimir** [comment]
Hi @slackerom, thanks for reporting this! We plan to solve this issue as part of: https://jira.mongodb.org/browse/COMPASS-4830.

**Comment by gribnoysup** [comment]
Thanks again for reporting! The fix should be available in the latest beta release 1.27.0-beta.4 and will be generally available when 1.27.0 is released completely
