### ISSUE TITLE
compass displays date time with configurable timezones

### ISSUE THREAD

**Issue by xuanyangyang** [mongodb-js/compass#2300]
compass displays date time with configurable timezones

**Comment by Anemy** [comment]
Here's this feature in our feedback portal: https://feedback.mongodb.com/forums/924283-compass/suggestions/39739636-allow-dates-to-be-viewed-in-local-time-instead-of
It allows for upvoting so we can get a better sense of how many users are interested in the feature.

Thanks for reporting! Hopefully we can get around to this soon.

**Comment by Anemy** [comment]
Going to close this as we're tracking this in the feedback portal and will get to it in time. Thanks again for opening this.
