### ISSUE TITLE
Timeout connecting to server after conversion to sharded cluster

### ISSUE THREAD

**Issue by mbrancato** [mongodb-js/compass#2302]
#### Current Behavior

I was testing converting a cluster in MongoDB Atlas from a replica set to a sharded cluster. All connections were made with a `mongodb+srv` URL. After conversion to a sharded cluster, the existing connection was still intact and I could refresh a collection. However, after closing and re-opening Compass, the connection would timeout (the URL did not change).

If I hit "New connection" and enter the same URL, it works. So now I have two connections in my recent history, with the same URL, but only one works. 

The URL looks like:
```
mongodb+srv://mike:xxxxxx@shard-test.zmqyf.mongodb.net/
```

I tried with no request parameters in the URL, and it still fails.

#### Expected Behavior/Code

A connection should still work if converting from a replica set to a sharded cluster.
#### Environment

- node.js / npm versions: n/a?
- OS: Max OS 11.4
- installed version: Version 1.26.1 (1.26.1)

#### Additional Context/Screenshots

I checked the network traffic with Wireshark because I thought it might be DNS, it was not. The connection would get established, but then the TCP connection would gracefully close and then Compass would complain.

![image](https://user-images.githubusercontent.com/8493275/123526182-175ec700-d6a4-11eb-9b08-58c38d5e7507.png)

**Comment by Treize2** [comment]
Same for me after upgrading to 1.27.0 I had to get the 1.26.1 back to get this working.

**Comment by mcasimir** [comment]
Hi @mbrancato @Treize2, could you also try 1.27.1?

**Comment by mcasimir** [comment]
@Treize2 where you connecting to `srv+mongodb` record too? Did you use any VPN?

**Comment by mcasimir** [comment]
It would also be helpful for us to know if you can connect with `mongosh`: https://github.com/mongodb-js/mongosh/releases/tag/v0.15.5

**Comment by Treize2** [comment]
@mcasimir The version 1.27.1 is still on timeout. 
The url used is : mongodb://<user>:<pwd>@<replicatset1>:27017,<replicatset2>:27017,<replicatset3>:27017/?authSource=<auth_db>&replicaSet=replicaset&readPreference=primary&ssl=false
I'll try the mongosh and will let you know

**Comment by mcasimir** [comment]
Ok I see! Yeah I hope `mongosh` would give us better insights. The connection string looks ok. Are you able to reach all the nodes in the replica set? Are there maybe nodes in the same replica set that may be not part of the connection string and that are not reachable?

**Comment by mcasimir** [comment]
@mbrancato for your case (replica set moved to sharded cluster) If you haven't already tried it you could recreate the connection with the "New Connection" button.

It may happen that some of the state from the previous cluster got saved in the connection (along with the favourite / history entry) and is causing issues when connecting to the new cluster. In that case recreating the connection would help.

<img width="252" alt="Screenshot 2021-07-07 at 16 13 47" src="https://user-images.githubusercontent.com/334881/124774731-53b0e380-df3e-11eb-8814-6eaeb5f7dad7.png">

**Comment by Anemy** [comment]
Pinging folks involved @Treize2 @mbrancato 
We've just released a new version of Compass, v1.31.0, with a number of improvements for connectivity and how we build, save, and load connections. You can download it here:
https://www.mongodb.com/try/download/compass
https://github.com/mongodb-js/compass/releases

This issue with the connection not persisting properly should be fixed with the changes - going to close this issue if that's alright. Please feel free to reopen if you update and this is still happening. Thanks for reporting the issue and helping improve Compass!
