### ISSUE TITLE
"Server selection timed out after 30000 ms" error in Compass 1.27.1

### ISSUE THREAD

**Issue by gribnoysup** [mongodb-js/compass#2320]
I seem to still be having connection timeout issues with the 1.27.1. When i roll back to 1.26.1 it works.

![image](https://user-images.githubusercontent.com/37958526/124326600-4960a500-db4c-11eb-8a27-2bb642b47334.png)

_Originally posted by @DrakeAnglin in https://github.com/mongodb-js/compass/issues/2311#issuecomment-873247789_

**Comment by gribnoysup** [comment]
@Anemy Yes, I am connecting to a replica set, readPreference=primary, ssl=true. Not sure what you're looking for on how im authenticating, but i am using our application functional account with admin access using the user name and password via the mongodb.net hostname.

_Originally posted by @DrakeAnglin in https://github.com/mongodb-js/compass/issues/2311#issuecomment-873271187_

**Comment by simon-bonnet** [comment]
Same

**Comment by simon-bonnet** [comment]
Also this is a stupid question but I can't find anywhere how to download the previous version, if anyone could  point me in the right direction that would be great thank you!

**Comment by BogdanDarius** [comment]
> Also this is a stupid question but I can't find anywhere how to download the previous version, if anyone could point me in the right direction that would be great thank you!

If you are using linux you can download previous versions from 
[https://downloads.mongodb.com/compass/mongodb-compass_VERSION_amd64.deb](https://downloads.mongodb.com/compass/mongodb-compass_VERSION_amd64.deb)
ex: [https://downloads.mongodb.com/compass/mongodb-compass_1.26.1_amd64.deb](https://downloads.mongodb.com/compass/mongodb-compass_1.26.1_amd64.deb)

**Comment by simon-bonnet** [comment]
Ah windows am afraid :( thanks though!

**Comment by gribnoysup** [comment]
Hey @simon-bonnet, you can find Compass builds in the releases tab on github, here's a [1.26.1 release](https://github.com/mongodb-js/compass/releases/tag/v1.26.1) for example. Also if you want to find a download center link for your OS, you can go to the [Compass download page](https://www.mongodb.com/try/download/compass) and select your platform, copy link intead of downloading it and replace the version in the URL

**Comment by simon-bonnet** [comment]
Ah I can search using the tags I see! Thanks!

**Comment by mcasimir** [comment]
Hi @DrakeAnglin, are you using an srv url? ie. `srv+mongodb://...` to connect to Atlas?

**Comment by mcasimir** [comment]
Another very helpful information would be if you could confirm you can connect with `mongosh`: https://github.com/mongodb-js/mongosh/releases/tag/v0.15.5

**Comment by DrakeAnglin** [comment]
@mcasimir yes, my connection string uses `mongodb+srv://`. I am not using VPN, i am on my corporate network, however this was not a issue with the previous version of compass. If i was on VPN or not it would work as our network team has opened up the ports for mongodb.

**Comment by mcasimir** [comment]
Fixed in 1.28.1, feel free to reopen if upgrading does not solve the issue.

**Comment by DrakeAnglin** [comment]
@mcasimir I Tried again today with the 1.28.1 update and i am still getting the timeout error. I rolled back to 1.26.1 and can connect immediately

**Comment by simon-bonnet** [comment]
Likewise

**Comment by mcasimir** [comment]
@DrakeAnglin @simon-bonnet we just released https://github.com/mongodb-js/compass/releases/tag/v1.31.0-beta.11 that contains a giant rework of the connectivity layer, please let us know if you still encounter issues with this version.
