### ISSUE TITLE
MongoDB 1.27.1 export to JSON does not allow to export without _id

### ISSUE THREAD

**Issue by NeverwinterMoon** [mongodb-js/compass#2329]
#### Current Behavior

- Press "Export collection"
- Press "Select fields"
- Deselect `_id`

Expecting JSON without `_id` fields
Actual: `_id` fields are exported

#### Environment

- node.js / npm versions: 14.16.0
- OS: macOS 11.4

**Comment by Anemy** [comment]
Hi @NeverwinterMoon - thanks for reporting this. We're tracking it in jira here: https://jira.mongodb.org/browse/COMPASS-4256 Hopefully we can get a fix out soon.

**Comment by Anemy** [comment]
Hi @NeverwinterMoon, We've just release 1.31.1 with a fix for this issue. You can download it here:
https://www.mongodb.com/try/download/compass
https://github.com/mongodb-js/compass/releases
Please feel free to reopen the issue if you update and this is still happening. Thanks again for reporting the issue and helping improve Compass!

**Comment by NeverwinterMoon** [comment]
Yes, I've already tried it out and it works like a charm. Thank you!
