### ISSUE TITLE
UI error on edit a document in JSON mode.

### ISSUE THREAD

**Issue by manudevcode** [mongodb-js/compass#2340]
#### Current Behavior

When you have two documents in edit mode and you update the first, the second marks as updated as well, even though you didn't click the save button for the second document.

#### Environment

- Compass Version 1.27.1 (1.27.1)
- OS: MacOs Big Sur

#### Possible Solution

Manage a separate state for editing each of the documents.

#### Additional Context/Screenshots

https://user-images.githubusercontent.com/11260098/125147677-6d932780-e0f2-11eb-8176-675a87afd2d9.mov

**Comment by Anemy** [comment]
Hi - thanks for reporting this - good writeup and video too. I was able to reproduce. Here's a ticket in jira we can track it in: 
https://jira.mongodb.org/browse/COMPASS-4941
I'll post back/close this when there's a fix out. Thanks again!

**Comment by Anemy** [comment]
Hi @manudevcode - we've included a fix for this in the most recent release `1.31.2`. Going to close this, feel free to reopen if you upgrade and the issue persists.
Thanks again for reporting this and helping improve Compass!
