### ISSUE TITLE
Server record does not share hostname with parent URI

### ISSUE THREAD

**Issue by xxSkyy** [mongodb-js/compass#2352]
#### Current Behavior

From over 6 months I cant normally connect to mongodb atlas normally, it only happens on Macbook, I've got this error:
https://imgur.com/a/w4xtcuf
And only way I can connect are manual paste clicking `fill in connection fields individually` then turn off compass, turn on, try to connect normally, click individial fill and connect, this way I can.
I did update compass just 5 mins ago, still same problem

#### Environment
 node: 16.4.2
 OS: OSX 11.4

**Comment by addaleax** [comment]
@xxSkyy What kind of deployment are you connecting to? This is tricky to debug without knowing the actual hostname in question or its SRV record.

Generally speaking, the error message in question occurs if the SRV record points to another domain than the SRV record itself, e.g. a `foo.mongodb.net` srv record cannot point to a host at `bar.google.com`.

**Comment by xxSkyy** [comment]
> @xxSkyy What kind of deployment are you connecting to? This is tricky to debug without knowing the actual hostname in question or its SRV record.
> 
> Generally speaking, the error message in question occurs if the SRV record points to another domain than the SRV record itself, e.g. a `foo.mongodb.net` srv record cannot point to a host at `bar.google.com`.

Its atlas connection copied from their recommended setting
`mongodb+srv://XXX:*****@XXX.b8gat.mongodb.net/`

**Comment by addaleax** [comment]
@xxSkyy Could you try to:

- Run `npx resolve-mongodb-srv <url>` where `<url>` is the srv url you are using and report back the result (with credentials removed, of course)?
- Run `nslookup -q=SRV _mongodb._tcp.<hostname>` where hostname is `XXX.b8gat.mongodb.net`

? That might help with debugging this :)

**Comment by xxSkyy** [comment]
> @xxSkyy Could you try to:
> 
>     * Run `npx resolve-mongodb-srv <url>` where `<url>` is the srv url you are using and report back the result (with credentials removed, of course)?
> 
>     * Run `nslookup -q=SRV _mongodb._tcp.<hostname>` where hostname is `XXX.b8gat.mongodb.net`
> 
> 
> ? That might help with debugging this :)

I think it's some problem of my mac, on other devices works fine and also on some other app I had hostname problems so I suppose its not issue for this place, anyway thanks for trying to help.
