### ISSUE TITLE
Connection failure, it just shows "Loading connection" with compass icon

### ISSUE THREAD

**Issue by webjoyable** [mongodb-js/compass#2365]
#### Current Behavior

As I already wrote it's just stuck to loading screen when I try to connect. I reinstalled it twice, no change.
I'm connecting using a MongoDB Compass string generated on mongodb.com website

#### Expected Behavior/Code

It should connect to the cluster

#### Environment

- node.js / npm versions:
- OS: Windows 10 21H1
- Compass Version: 1.28.1

#### Additional Context/Screenshots

![image](https://user-images.githubusercontent.com/28753190/126763230-ebae3b57-076c-4bd4-8448-dda46087b935.png)

**Comment by addaleax** [comment]
@webjoyable Can you share any more information about how you are trying to connect? E.g. whether you are connecting using a connection string, and if so, what format that has (minus credentials/actual host names of course), whether you are connecting using a SRV record, what your TLS settings are, etc.

Also, knowing the Compass version might be helpul here.

**Comment by webjoyable** [comment]
I manage to connect when I clicked "Favorite" icon before clicking on "Connect" button

**Comment by webjoyable** [comment]
My bad. It was my DNS server issue, when I changed back to "Obtain DNS server automatically" and flushed DNS, it works perfectly.
