### ISSUE TITLE
Feature Request: MacBook touch bar support

### ISSUE THREAD

**Issue by manudevcode** [mongodb-js/compass#2384]
## Feature Request
Touch bar support for macbooks

## Detailed Description

Add some actions on the macbook's touchbar like vs code

<img width="1004" alt="Captura de Touch Bar 2021-08-04 a la(s) 16 13 36" src="https://user-images.githubusercontent.com/11260098/128255709-3a1141cd-4180-457e-87e1-2f89fddadb3b.png">

**Comment by Anemy** [comment]
Hi @manudevcode if it's alright with you I'm going to close this since the newer macs don't have touchbar support it's probably not worth spending too much time implementing support.
