### ISSUE TITLE
Mongo Compass online request

### ISSUE THREAD

**Issue by bucibucii** [mongodb-js/compass#2386]
## Question
Why mongo compass is sending data to an online api call?

**Comment by Anemy** [comment]
Hi @bucibucii Compass uses a few online api calls for things like checking for auto updates, crash reports, telemetry, etc.
These can be viewed and disabled in the `Privacy Settings` tab:
<img width="390" alt="Screen Shot 2021-08-06 at 10 44 23 AM" src="https://user-images.githubusercontent.com/1791149/128528493-8719c6b0-cf10-4eef-85a0-17179b04f9eb.png">
<img width="610" alt="Screen Shot 2021-08-06 at 10 44 44 AM" src="https://user-images.githubusercontent.com/1791149/128528491-f83bc9fd-2e12-46f0-9cf6-c43231c49288.png">
We also have an `Isolated` release which disables all network connections except the connection to the MongoDB instance.

Going to close this if that's alright, thanks for checking out Compass - let me know if that answers your question.
