### ISSUE TITLE
GUI Browser keeps on loading the collection

### ISSUE THREAD

**Issue by tbhaxor** [mongodb-js/compass#2394]
#### Current Behavior

On connecting to DB, the GUI browser stuck while performing query but aggregations are working fine. I have to then disconnect, reconnect to the same db and perform another query. 

The same is happening with mongo sh.

I can only run one query either in the integrated terminal or the browser and then this issue occurs.

#### Code/Gist

_Perform simple find operation, Check screenshot_

#### Expected Behavior/Code

It should work seamlessly

#### Environment

- node.js / npm versions: v14.17.4 / 7.20.5
- OS: Arch Linux (Manjaro)

#### Additional Context/Screenshots

![Screenshot_20210814_165820](https://user-images.githubusercontent.com/28386721/129445543-6fee007c-9cde-4f1f-bec8-bbe3a19a68c6.png)

**Comment by tbhaxor** [comment]
In this case, I had first perform findOne in the terminal and then later in the browser

**Comment by Anemy** [comment]
Hi @tbhaxor - a few questions to help us understand what's going on here so that we can hopefully fix. Is this with Compass 1.28.1? How many documents are in the collection? Do you have another connection you can try Compass with? Does it act the same then?
Thanks for reporting! Happy you were able to get it working with the beta.

**Comment by tbhaxor** [comment]
> Is this with Compass 1.28.1?

Yes. Please note in version 1.27.0,  it is working like a charm



> How many documents are in the collection?

14



> Do you have another connection you can try Compass with? Does it act the same then?

Yes

**Comment by Anemy** [comment]
@tbhaxor We've just released 1.31.0 which has a number of improvements in Compass and we've also removed the loading overlay that used to show. If it's alright with you can you see if this new version fixes the issue?
https://www.mongodb.com/try/download/compass
https://github.com/mongodb-js/compass/releases
We've also improved our log reporting in Compass so if you open logs here:
<img width="553" alt="Screen Shot 2022-04-01 at 2 34 26 PM" src="https://user-images.githubusercontent.com/1791149/161322122-08398ae3-b7a1-4721-ae9c-826eb608467d.png">

There might be something for us to use to debug if this issue persists. I don't think we've seen this issue come up before and we aren't sure on the cause just yet.
