### ISSUE TITLE
Bug Report: Exporting to JSON file Integer fields with large numbers change slightly

### ISSUE THREAD

**Issue by f11y11** [mongodb-js/compass#2452]
#### Current Behavior

Integer fields with large numbers change slightly upon exporting to a JSON file

#### Expected Behavior/Code

Exported JSON document should not have changed integer fields

#### Environment

- node.js / npm versions: node: 12.18.4 npm: 6.14.6
- OS: Windows 11

**Comment by Anemy** [comment]
Hi @f11y11 - thanks for reporting this issue. We've included a fix in the most recent release `1.31.2`
It's available for download here:
https://www.mongodb.com/try/download/compass
https://github.com/mongodb-js/compass/releases
For book keeping here's a jira ticket we used for tracking this fix: https://jira.mongodb.org/browse/COMPASS-4694

Going to close this, feel free to reopen if the issue persists. Thanks again for reporting this and helping improve Compass.
