### ISSUE TITLE
Allow defining variables in aggregations tab

### ISSUE THREAD

**Issue by guludo** [mongodb-js/compass#2518]
## Detailed Description

It would be nice if there was a way to define variables to be used in different stages of the pipeline. They would differ from mongo's notion of variables in a pipeline: they would be values that would be used from variables from the programming language using the pipeline.

- When creating/editing the pipeline, the user can define values for such variables, which would be a nice way of testing the pipeline with different inputs.
- When exporting the pipeline for a given language, the generated text would have references to the variables in the format expected by the language.

For example, let's say I want to define a variable `textSearch`. I would create that in a UI component, where I could define variable names and their values. Then I could use them in the aggregation stages by just making references by name, as in the `$match` stage below:

```
{
    $text: {
        $search: textSearch
    }
}
```

Note that this is a very simple example. But this feature would really come in handy when I need to use the variable in more than one stage. As of now, I currently need to replicate the values directly in each stage and, when exporting to my programming language, I need to replace each occurrence with the respective variable name.

**Comment by Anemy** [comment]
Hi @guludo - this is something that would be better suited for our feedback forum: https://feedback.mongodb.com/forums/924283-compass
From a quick search, this might be what you're looking for:
https://feedback.mongodb.com/forums/924283-compass/suggestions/44239251-possibility-to-set-variables-used-in-pipeline-stag

The feedback forum allows for upvoting features so we can have a better sense of how many folks are interested in it and how we can prioritize it. The github issues are better for smaller issues and bug reports. Thanks for bringing this up.

A bit more context, we're currently planning out how to improve our aggregation editing experience currently to provide more of a editor experience. Hopefully that'll be some improvements and a step towards this feature.
