### ISSUE TITLE
Custom favorites name is displayed as "Local" after connecting to remote

### ISSUE THREAD

**Issue by travis5491811** [mongodb-js/compass#2520]
#### Current Behavior

After following the steps defined [here](https://docs.mongodb.com/compass/current/connect/favorite-connections/) for naming favorites, the name is saved. But after I close everything and open compass and connect to the named favorite connection, the name displayed is the default "Local". If I go and rename "Local" after I've connected, the system creates a second favorite instance.

#### Environment

- Compass version 1.28.4
- OSX 10.15.7

**Comment by Anemy** [comment]
Hi @travis5491811 - just some context - we're currently in the process of updating the way we store, load, and use connections in Compass. I haven't been able to reproduce, but this issue should go away in the next release or two.

**Comment by Anemy** [comment]
@travis5491811 Should be fixed in 1.31.0 - thanks for reporting the issue! Going to close this, feel free to open if you upgrade and you're still seeing `Local` after you've saved a connection with a name.
