### ISSUE TITLE
Collection menu item is not showing up in MacOS

### ISSUE THREAD

**Issue by herberthobregon** [mongodb-js/compass#2587]
## Bug Report
Collection menu item is not showing up in MacOS
#### Current Behavior
v.latest
![image](https://user-images.githubusercontent.com/6503845/141610495-aaa903e7-6376-4c1d-b692-8672dd257d3c.png)

![image](https://user-images.githubusercontent.com/6503845/141610479-1f00de23-0840-46cd-ad23-ceecfac45bb3.png)

#### Environment

```
  System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 699.70 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.4.2 - ~/.nvm/versions/node/v16.4.2/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v16.4.2/bin/yarn
    npm: 7.18.1 - ~/.nvm/versions/node/v16.4.2/bin/npm
  Browsers:
    Brave Browser: 95.1.31.91
    Chrome: 95.0.4638.69
    Firefox: 94.0.1
    Safari: 14.1.2
  npmPackages:
    vite: 2.6.12 => 2.6.12 
```

#### Possible Solution

Downgrade version

#### Additional Context/Screenshots
The documentation is obsolete 
https://docs.mongodb.com/compass/current/import-export/

**Comment by gribnoysup** [comment]
Thanks for the report @herberthobregon, I can confirm that the issue exists and opened a JIRA ticket where you can track the progress for the fix https://jira.mongodb.org/browse/COMPASS-5290
