### ISSUE TITLE
Current topology does not support sessions. When connecting to old standalone 2.4.

### ISSUE THREAD

**Issue by lagc03** [mongodb-js/compass#2590]
#### Current Behavior

When fetching documents from a collection, the GUI just displays the following error:
Current topology does not support sessions.

#### Expected Behavior/Code

Display the documents regardless of the topology.

#### Environment

- node.js / npm versions: n/a
- OS: WIndows 10
-  MongoDB Compass: 1.29.4

#### Possible Solution

DO not enforce topology setting for connections with legacy versions of MongoDB.

I am using current versions of MongoDB compass to access legacy MongoDB standalone databases currently in production environment. For now I will try to downgrade my compass version and disable updates....

**Comment by addaleax** [comment]
> I am using current versions of MongoDB compass to access legacy MongoDB standalone databases currently in production environment. For now I will try to downgrade my compass version and disable updates

That sounds like the right solution here, tbh. MongoDB 2.4 has been unsupported for a very long time, and we probably wouldn’t fix bugs that only reproduce with versions that old.

**Comment by ToTheHit** [comment]
Same problem with MongoDB 3.4.9

**Comment by gribnoysup** [comment]
Hey @ToTheHit, Compass requires your MongoDB version to be [at least 3.6 to work properly](https://docs.mongodb.com/compass/current/install/#software-requirements). We are not trying to break compat for the older versions on purpose, but as @addaleax mentioned above, we are not planning to maintain compatibility with these versions forever, so you should expect some things to now work property. If you want to continue using Compass with unsupported MongoDB version, you can downgrade to the version that will work for you. Sorry for the inconvenience and thanks for using the app!

**Comment by matthew-b-payne** [comment]
> Hey @ToTheHit, Compass requires your MongoDB version to be [at least 3.6 to work properly](https://docs.mongodb.com/compass/current/install/#software-requirements). We are not trying to break compat for the older versions on purpose, but as @addaleax mentioned above, we are not planning to maintain compatibility with these versions forever, so you should expect some things to not work property. If you want to continue using Compass with unsupported MongoDB version, you can downgrade to the version that will work for you. Sorry for the inconvenience and thanks for using the app!

Our version is 3.6.6.  We get this error as well.  According to your message it should work with 3.6?


![image](https://user-images.githubusercontent.com/1139755/143125154-c2ec163c-2aed-42c7-962a-295748953593.png)

**Comment by yurtaev** [comment]
The same issue on mongo v3.6

![CleanShot 2021-12-03 at 11 22 57](https://user-images.githubusercontent.com/444503/144539743-903e3405-d2dc-438e-8ae5-085829a4441f.jpg)

**Comment by tanmaybhatt** [comment]
Worked after downgrading to 1.26.0

**Comment by gribnoysup** [comment]
@matthew-b-payne @yurtaev can you check what feature compatibility version your server is configured to? You can do it with `getParameter` command:

```
db.adminCommand({ getParameter: 1, featureCompatibilityVersion: 1 })
```

And if it's less than 3.6, you can switch it with [`setFeatureCompatibilityVersion`](https://docs.mongodb.com/manual/reference/command/setFeatureCompatibilityVersion/) command

**Comment by jcrochet-24s** [comment]
Same with DocumentDB 3.6 hosted on AWS.
Downgrading to 1.28.4 solve the problem.
![image](https://user-images.githubusercontent.com/88405572/145250211-a5bae941-f543-484c-8059-c5ad941f30fc.png)

**Comment by gribnoysup** [comment]
[DocumentDB doesn't seems to support](https://docs.aws.amazon.com/documentdb/latest/developerguide/mongo-apis.html#mongo-apis-dababase-sessions) starting sessions in their 3.6 version
