### ISSUE TITLE
Apple M1 problems

### ISSUE THREAD

**Issue by saurikCornel** [mongodb-js/compass#2597]
Version 1.17 works nice, but all new versions freezes as hell on apple silicone when i hiding a window. Now I downgraded to 1.17 and everything ok.  Is there any plan to build native arm version for Mac? Thank you!

**Comment by Anemy** [comment]
Hi @saurikCornel can you confirm if this still persists in the latest beta? (1.31.0-beta.6 at the time of writing)
https://github.com/mongodb-js/compass/releases

We've got access to an m1 and aren't seeing this behavior. Are you trying a version after 1.29.4? That was when we updated electron to 12, which probably fixed this.
