### ISSUE TITLE
Collections fail to load on the serverless databases

### ISSUE THREAD

**Issue by hensansi** [mongodb-js/compass#2598]
I'm creating an issue on github so others are aware. 
https://jira.mongodb.org/projects/COMPASS/issues/COMPASS-5305

#### Current Behavior

When accessing the documents through the collections UI the loader gets stuck. This only happens with [serverless databases](https://www.mongodb.com/cloud/atlas/serverless).

Querying through the shell works.

#### Expected Behavior/Code
The documents are loaded under the collections

#### Environment
- OS: Arch Linux
- Compass version: 1.29.4

#### Possible Solution
Downgrade to [1.28.4](https://aur.archlinux.org/cgit/aur.git/commit/?h=mongodb-compass&id=d3086626e1df494115fc4d0437c4c0b2f2d650bb)

#### Additional Context/Screenshots
Attached on the [JIRA ticket](https://jira.mongodb.org/projects/COMPASS/issues/COMPASS-5305)

**Comment by Anemy** [comment]
Here's an updated ticket number https://jira.mongodb.org/browse/COMPASS-5299

1.29.5-beta.5 is out with a fix: https://github.com/mongodb-js/compass/releases/tag/v1.29.5-beta.5
This fix will be in the next release.
Thanks for opening the issue!

**Comment by hensansi** [comment]
Yup, I can confirm it is working on the 1.29.5-beta.5
