### ISSUE TITLE
MacOS app not notarised

### ISSUE THREAD

**Issue by tomsturge** [mongodb-js/compass#2682]
## Question

My company is CyberEssentials and ISO27001 certified and have to be compliant with some security requirements. The Compass app isn't notarised and this means we can't use the app for our DB on Mongo Atlas. When will this be resolved?

**Comment by addaleax** [comment]
@tomsturge Can you specify the exact file you are downloading (incl. URL)? All recent versions of Compass should be properly signed and notarized.

**Comment by tomsturge** [comment]
We have a version from Oct 2021 in our self service software portal, will try updating it to see if the problem persists and get back to you
