### ISSUE TITLE
No longer supports legacy MongoDB v3.4 

### ISSUE THREAD

**Issue by ingles98** [mongodb-js/compass#2699]
After the latest updates I can no longer connect via Compass to any 3.4 MongoDB Community Servers at all. Was this intended ? I couldn't find anything regarding this on the changelogs.

**Comment by Anemy** [comment]
Hi @ingles98  Compass requires your MongoDB version to be at [least 3.6 to work properly](https://docs.mongodb.com/compass/current/install/#software-requirements). We are not trying to break compat for the older versions intentionally, but we are not planning to maintain compatibility with these versions forever, so you should expect some things to not work property. If you want to continue using Compass with unsupported MongoDB version like 3.4, you can downgrade to the version that will work for you. Sorry for the inconvenience and thanks for using the app!
