### ISSUE TITLE
Initial setup fails for node 16 and npm 8 versions

### ISSUE THREAD

**Issue by RohanAntony** [mongodb-js/compass#2812]
## Bug Report
npm run bootstrap and also npm install fails on windows.

#### Current Behavior
![image](https://user-images.githubusercontent.com/5779016/154836985-a3fb9c6c-8650-467c-b2a1-3899687d8875.png)
Package.json file mentions the version as 
"engines": {
  "node": ">=14.17.5",
  "npm": ">=7.16.0"
},

I tried using nvm for windows to downgrade node to 15 and npm to 7. Still seeing the same error.
![image](https://user-images.githubusercontent.com/5779016/154837846-067403f4-3941-4644-8834-e957cda415c1.png)

**Comment by RohanAntony** [comment]
The official version [index.json](https://nodejs.org/dist/index.json) used by nvm doesn't support npm v7 with node v14. Also, `npm install --ignore-engines` fails too.

**Comment by Anemy** [comment]
Hi @RohanAntony thanks for checking out the project, is it possible to use nvm to go to node v14 and then use `npm install -g npm@7` to get npm to the correct version? Let me know if that works for you!
