### ISSUE TITLE
Bug Report 1-30.1 Validation tab shows nothing

### ISSUE THREAD

**Issue by HawkAPFM** [mongodb-js/compass#2836]

**Comment by Anemy** [comment]
Hi @HawkAPFM - I haven't been able to reproduce this, could you share your logs (be sure to retract any sensitive information) or any other information for us to help debug the issue?
<img width="276" alt="Screen Shot 2022-02-24 at 1 31 37 PM" src="https://user-images.githubusercontent.com/1791149/155585646-cdcae401-7096-451c-b900-243b3ab2aa90.png">

<img width="667" alt="Screen Shot 2022-02-24 at 1 33 43 PM" src="https://user-images.githubusercontent.com/1791149/155585928-ecce45eb-0813-41db-9bf5-7d0372722856.png">
