### ISSUE TITLE
Aggregations preview is limited to 150px height 

### ISSUE THREAD

**Issue by MuthSW** [mongodb-js/compass#2993]
## Bug Report
When writing an Aggregation, the preview output (Output after ... stage) has a fixed limit of 150px, even if there is more space available.
(eg: stage-editor-module-stage-editor-container__2z3c3 has a size of 388x1581)

This was working in an older version (think, from half a year ago), but not with 1.31.1 & 1.31.2

#### Environment
- OS: Ubuntu 20.04

#### Possible Solution

my workaround

disable "height: 150px;" for Element
".stage-preview-module-stage-preview-document-card__3v-vS"

**Comment by Anemy** [comment]
Hi @MuthSW Thanks for reporting this issue, definitely looks like a new bug. Sorry for the inconvenience, hopefully we can get a fix out soon.
I've created a ticket in jira to track a fix: https://jira.mongodb.org/browse/COMPASS-5746
We'll post back here when there's an update.

**Comment by MuthSW** [comment]
Great, thx.

**Comment by Anemy** [comment]
@MuthSW Thanks for reporting! We've just released [v1.31.3](https://github.com/mongodb-js/compass/releases/tag/v1.31.3) with a fix for this issue. Going to close this issue, if you update and find the issue persists feel free to reopen. Thanks again for catching this and helping us improve Compass!

https://github.com/mongodb-js/compass/releases
