### ISSUE TITLE
Don't see connections on Recents

### ISSUE THREAD

**Issue by TylerL19** [mongodb-js/compass#2994]
#### Current Behavior

When I connect a database on Azure CosmosDB and I disconnect it. I don't see the connection on Recents.

#### Expected Behavior/Code

I will see the connection on Recents

#### Environment

- OS: macOS 12.3.1 - Apple Silicon Chip

**Comment by Anemy** [comment]
Hi @TylerL19 it looks like the default connection string Azure Cosmos DB supplies to users is in a format which contains unescaped characters in the `password` and `appName` (in mine it was the `=` key in the password and the `@` key in appName).
If you enter the password and appName in using the connection form in the `Advanced Connection Options` dropdown it should automatically escape these characters and is a solution to the issue.

The connection string is successfully saved, however in our loading of the connection we detect the the unescaped character and fail to load. I think this is a bug in our connection form not erroring on the unescaped characters before connecting/saving. I've created a jira ticket to track a fix: https://jira.mongodb.org/browse/COMPASS-5745
Thanks for reporting the issue.

Does your connection string have unescaped characters in the password or appName? Does it work as expected when those characters are escaped? (`=` -> `%3D` for instance)

**Comment by TylerL19** [comment]
Hi @Anemy , appName and Password of our connection string contains unescaped characters. Sorry for late response. Please help to fix this as soon as possible. This issue make us hard to reopen recents connections. Thank you very much!

**Comment by Anemy** [comment]
This was fixed and release in Compass `1.32.5` - sorry for the late update. Closing this now, feel free to reopen if you upgrade and find the issue still persists. Thanks for reporting this and helping improve Compass!
