### ISSUE TITLE
The _MONGOSH in version 1.32.0 can not prompt for info.

### ISSUE THREAD

**Issue by RealMuDao** [mongodb-js/compass#3009]
I have to spell every letter.

**Comment by Anemy** [comment]
Looks like we've got a ticket in jira to track this bug: https://jira.mongodb.org/browse/COMPASS-4760
We'll post back here when there's an update. Thanks for reporting!

**Comment by RealMuDao** [comment]
> Looks like we've got a ticket in jira to track this bug: https://jira.mongodb.org/browse/COMPASS-4760 We'll post back here when there's an update. Thanks for reporting!
> 
> It looks like autocomplete works in the embedded mongosh when the connection is first connected to, however the autocomplete stops working after using the aggregation editor (a bug with how the editor singleton is currently handled). As a workaround it's possible to connect and not use the aggregation editor if you need autocomplete results, and then in a new window utilize the rest of the impacted editors. Sorry for the inconvenience.

Thank you very much!

**Comment by Anemy** [comment]
@RealMuDao Looks like this is fixed in the new `1.34.0-beta.1` release. This'll land in the 1.34.0 release when it happens. 
Going to close this, feel free to reopen when you update if things aren't as expected. Thanks to @gribnoysup for the fix and @addaleax for pulling it into Compass. 
Thanks again for bringing this up!

**Comment by RealMuDao** [comment]
> @RealMuDao Looks like this is fixed in the new `1.34.0-beta.1` release. This'll land in the 1.34.0 release when it happens. Going to close this, feel free to reopen when you update if things aren't as expected. Thanks to @gribnoysup for the fix and @addaleax for pulling it into Compass. Thanks again for bringing this up!

I am glad to hear that, thanks.
