### ISSUE TITLE
Timezone setting to display date in UTC datatype in local time zone

### ISSUE THREAD

**Issue by azmhyy2021** [mongodb-js/compass#3012]
## Feature Request
Timezone setting to display date in UTC datatype in local time zone

## Context
It's great feature that MongoDB forces the users to use UTC timezone for the database settings,
however on the Compass, I need to calculate the time to know the local time from the date in UTC data type always.
It's annoying and sometimes make a mistake when I make a decision.
So, I request the above feature to be implemented.

Thank you

**Comment by Anemy** [comment]
Hi @azmhyy2021 - thanks for the good suggestions. I think that's something we'd like to implement. 

A bit of context, we're looking into adding some more general settings controls for Compass and I think this would likely land after we have that customizing settings ability.
 
Going to close this issue as a duplicate if that's alright, we have https://github.com/mongodb-js/compass/issues/2300 already.

**Comment by yuhongshuai** [comment]
please I want set timezone ，thank you
