### ISSUE TITLE
Bug Report: Saved connections not loading

### ISSUE THREAD

**Issue by Giotje** [mongodb-js/compass#3094]
#### Current Behavior

I cannot see favorited connections under favorites and i can't see my recent connections under recents when re-opening the app

#### Expected Behavior/Code

To see favorited and recent connections when re-opening the app

#### Environment

- OS:
Arch Linux x86_64 

- Kernel:
5.17.5-arch1-2

**Comment by Anemy** [comment]
@Giotje A few questions to help us debug this issue:
- Compass uses the system's credential store to store connections, does your system have an available credential store like GNOME Keyring installed? https://www.mongodb.com/docs/compass/current/connect/favorite-connections/#considerations
- Does this happen for all connections? Local/Remote and different connection/authentication configurations?
- If the 2nd question is that it is only for some connections, what is the shape of the connection string? Authentication mechanism, srv, etc.

**Comment by Giotje** [comment]
let me see if i have a keyring installed, and then come back to you

**Comment by Giotje** [comment]
yo i installed the keyring and all the servers showed up. thank u man. much love
