### ISSUE TITLE
Bug Report: mongodb-language-model npm package

### ISSUE THREAD

**Issue by michael-rivera-florencehc-com** [mongodb-js/compass#3119]
NodeJS npm package mongodb-language-model, not accepting valid mongo query 

#### Current Behavior

I am dynamically building queries against a mongodb database. In doing this I am using query checking, using a library called 'mongodb-language-model'. It has proven to work great for many of the queries I have run. 

However, when using this library against the following query:

{"name":"temp","$or":[{"binderId":"627e38f6e5ce...."},{"$expr":{"$eq":[{"$last":"$lineage"},"627e38f6e5ce15..."]}}],"teamId":"627e35b9e5ce..."}

I get the error:

```
SyntaxError: Expected "$binary", "$date", "$maxKey", "$minKey", "$numberDecimal", "$numberLong", "$oid", "$ref", "$regex", "$timestamp", "$undefined", or [^$] but "$" found.
```

This query returns a list of documents, matching based on the last item in an array within a document along with some other matches.
 
I have verified that if I use this query in a find like so it works fine:

```
db.collection.find({"name":"temp","$or":[{"binderId":"627e38f6e5ce...."},{"$expr":{"$eq":[{"$last":"$lineage"},"627e38f6e5ce15..."]}}],"teamId":"627e35b9e5ce..."})
```

I have tracked it down the to the usage of $last which is an [alias](https://www.mongodb.com/docs/manual/reference/operator/aggregation/last-array-element/) for 

{ $arrayElemAt: [ <array expression>, -1 ] }

I attempted to use this version of the expression in the query but still it fails with the same error with the library.

#### Expected Behavior/Code
a list of docuements based on the query 

#### Environment
NodeJS - v14.18.1
NPM - 8.9.0
OS - 12.3.1

#### Possible Solution

An alternate query that would provide the equivalent information

**Comment by Anemy** [comment]
Looks like we're currently using the [`mongodb-language-model`](https://github.com/mongodb-js/mongodb-language-model) in Compass through the [`query-parser`](https://github.com/mongodb-js/query-parser) package:
https://github.com/mongodb-js/query-parser/blob/24d4426dc2f50e86cd4b60675cff750d3be033a2/lib/index.js#L96

So this bug would impact Compass when using the `$expr` command in the query bar as it would show using `$last` (or other aggregation expressions used) in a filter as invalid. [`$expr`](https://www.mongodb.com/docs/manual/reference/operator/query/expr/#mongodb-query-op.-expr) was added in MongoDB 5.0
An example of a query that shows as invalid in the query bar is:
```ts
{$expr: {$eq: [{$arrayElemAt: ["$array", -1]}, '123']}}
```
While in [mongosh](https://www.mongodb.com/docs/mongodb-shell/) this query is valid.
```ts
db.raw_subway_entrances_2018.find({$expr: {$eq: [{$arrayElemAt: ["$array", -1]}, '123']}})
```

I'll have to double check with the team on when we archived [`mongodb-language-model`](https://github.com/mongodb-js/mongodb-language-model) and if it's something we want to support going forward.

A bit more context:
Looks like the language model is something we moved into the mono repo but then later removed, here's a commit where it still exists:
https://github.com/mongodb-js/compass/tree/792af7c2e8f78264e74f17a1983dd1c57e8d15a6/packages/mongodb-language-model
This was likely around the time that 5.0 was added, so this could have been missed as something we'd need to maintain going forward. I'm not aware of a future plan of support.

In the interim I'm not sure there's something that verifies the language in quite the same way as that package does, however, the MongoDB node js library is now in typescript and may provide some typing support for these things. This is probably not something for the `Compass` project.
I'll have to check with the team and see if there's more context for this one and how we will want to proceed. Giving support for allowing `$expr` aggregation expressions inside of queries is something we want to allow in Compass. Thanks for reporting this.
