### ISSUE TITLE
Recent Update 1.3.13 Past Queries don't retrain functions 

### ISSUE THREAD

**Issue by mixeract** [mongodb-js/compass#3129]
#### Current Behavior

UI recent updates has caused the Past queiries to lose the function.
Steps to reproduce 
1. In Filter type 
 { userid: NumberLong(894303306233552937) }
2. Open Past Queires Pane, history looks good
3. click on another database 
4. return to the first db and open the history pane. you will see the NumberLong function is lost and the query will look like {userid: 894303306233552900}

#### Expected Behavior/Code

The function shouldn't be lost 

#### Environment
Compass, recent release, 1.31.3
- OS: MacOS 

#### Possible Solution

na
#### Additional Context/Screenshots

na

**Comment by himanshusinghs** [comment]
Closing this issue as it has been addressed as part of [COMPASS-7824](https://jira.mongodb.org/browse/COMPASS-7824). If you continue to face problem please feel free to re-open this issue.
