### ISSUE TITLE
Release on flathub [Linux]

### ISSUE THREAD

**Issue by mijorus** [mongodb-js/compass#3188]
## Feature Request
Add Mongo Compass to Flathub for easier distribution and updates

## Detailed Description
Flathub is a store for flatpaks apps:
https://flathub.org/home

## Context
Makes it easier to install and update Compass

## Possible Implementation
I'm working on it:

https://github.com/flathub/flathub/pull/3269

If someone involved in the project is interested in maintaining it, please reply to this thread

**Comment by Anemy** [comment]
Hi @mijorus - this is something that would be better suited for our feedback forum: https://feedback.mongodb.com/forums/924283-compass
From a quick search, this might be what you're looking for:
https://feedback.mongodb.com/forums/924283-compass/suggestions/45344404-mongodb-compass-on-flathub

The feedback forum allows for upvoting features so we can have a better sense of how many folks are interested in it and how we can prioritize it. The github issues are better for smaller issues and bug reports.

 Thanks for bringing this up, going to close this, feel free to reopen.
