### ISSUE TITLE
Compass crash when editing big documents

### ISSUE THREAD

**Issue by snird** [mongodb-js/compass#3303]
When editing a document as JSON, and copying a big JSON output (>1MB typically) the entire app crashes.

Apps like Studio 3T don't crash, as they recognize the file is big and thus optimize the editor:
![image](https://user-images.githubusercontent.com/2139589/181918030-611a8aa4-5ae8-4f96-983b-cfb08297f2be.png)

It would be nice to have Compass able to handle big files too.

**Comment by gribnoysup** [comment]
Hey @snird, thanks for taking your time to report the issue! Can you try this with Compass v1.35.0 please? We did some work specifically around json editor view and json list in general to improve performance and wondering whether or not it scales well for documents that are that big

**Comment by snird** [comment]
Thank you @gribnoysup,
the editor can handle big files just fine now.
