### ISSUE TITLE
[Feature Request] Support Multi Language

### ISSUE THREAD

**Issue by sillysillyc** [mongodb-js/compass#3414]
Would Mongodb Compass consider supporting muti language or just expose a way to allow community to help translating ?

**Comment by feliciahsiehdb** [comment]
Do you mean a spoken/written language or a programming language for code snippets?

**Comment by sillysillyc** [comment]
@feliciahsiehdb like Chinese、Japanese and other languages for GUI

**Comment by Anemy** [comment]
That's a good suggestion, as far as I know we haven't looked into providing a way for folks to translate. I'll see if there's anything we have tracked on this currently.

**Comment by Anemy** [comment]
Chatted with the team, this isn't on the roadmap currently, and we're not sure how requested of a feature it is. If this is something you'd like can you upvote it in our feedback forum?
I created a suggestion for it here: https://feedback.mongodb.com/forums/924283-compass/suggestions/45664513-add-support-for-languages-localization-internati

By upvoting it we can get more of a sense of how many folks are interested in it and you can also get notified when we've started working on it and released it.
If it's alright with you I'm going to close this issue and we can use that to track it. Thanks for opening!
