### ISSUE TITLE
Fields missing when exporting collection

### ISSUE THREAD

**Issue by Gowee** [mongodb-js/compass#3423]
#### Current Behavior
By clicking the "Export Collection" icon button, some fields are missing in the popup window and in the exported JSON.

#### Code/Gist
N/A

#### Expected Behavior/Code
All fields are listed in the popup window. Otherwise, at least they are present in the exported JSON if "all" is checked.

#### Environment

- Client: mongodb-compass-isolated-bin 1.32.6-1
- Server: MongoDB 5.0 on MongoDB Cloud

#### Possible Solution
It seems that the MongoDB GUI tries to list fields based on a small portion of samples of the whole collection, for users to choose which to export in the popup window. But such a list is non-exhaustive. In my case, the collection is populated by a web crawler and fields are not in a well-defined schema. MongoDB GUI should have managed to export all fields even though they are not included in the samples.

**Comment by addaleax** [comment]
Hey @Gowee – Thanks for the report!

You are right as to what causes this, and we are aware of this pain point. We are currently in the design phase for an overhaul of our import/export functionality, and addressing this issue is absolutely going to be part of that.

I don’t think we have any public documents/tickets that I could link to for tracking this yet, though.

**Comment by Gowee** [comment]
Hi @addaleax.
Thanks for your kind reply and the excellent project. Looking forward to the new design.

**Comment by Gowee** [comment]
Should I close the issue for now?

**Comment by addaleax** [comment]
@Gowee Up to you! The alternative would be us commenting here to let you know once there’s an internal ticket to follow up on.

**Comment by hendrikserruys** [comment]
Any update on this issue?

**Comment by gribnoysup** [comment]
Okay, just double-checked, and you can add yourself to the watchlist on COMPASS-6428 to get notified when we start tackling this

**Comment by Anemy** [comment]
The newly released Compass `1.37.0` with the new import and export flow makes this a thing of the past! You can now include a projection in your query and it'll be used when exporting results.
You can find it here: https://github.com/mongodb-js/compass/releases
Thanks again for opening up the issue.
