### ISSUE TITLE
Bug Report: document/index count not updated when clicking on collection tab

### ISSUE THREAD

**Issue by Mosallamy** [mongodb-js/compass#3491]
#### Current Behavior
When opening collections in a new tab, then clicking a collection tab button, the document/index count does not change and only reflects the count for the last opened collection.

#### Expected Behavior/Code
Clicking on a collection tab should update document/index count

#### Environment

- **node.js:** 17.9.0
- **npm:** 8.5.5:
- **OS:** OSX 12.0.1 iMac M1 2021
- **MongoDB Compass:** 1.33.1

#### Additional Context/Screenshots

1. "Invoice_Item" has 4 documents
<img width="855" alt="Screen Shot 2022-09-18 at 2 18 15 PM" src="https://user-images.githubusercontent.com/49591985/190899856-3ff3f483-37bd-4060-a581-36f10bbfe5b7.png">

2. Clicking on "products" collection tab still shows the count as 4 document, which should be 193

<img width="854" alt="Screen Shot 2022-09-18 at 2 18 19 PM" src="https://user-images.githubusercontent.com/49591985/190899899-de600374-c954-44a5-9479-49b8951f7436.png">

3. Clicking on the "products" collection from the sidebar shows the correct count
<img width="251" alt="Screen Shot 2022-09-18 at 2 18 43 PM" src="https://user-images.githubusercontent.com/49591985/190899678-cabc9597-fbbe-4224-ade7-0bd221ef6707.png">

4. "products" collection now shows correct document count
<img width="855" alt="Screen Shot 2022-09-18 at 2 18 49 PM" src="https://user-images.githubusercontent.com/49591985/190899680-c9d4daa1-2aea-4b38-b7c5-ee683a48ca91.png">

**Comment by mabaasit** [comment]
@Mosallamy thanks for reporting this issue. I've opened [ticket](https://jira.mongodb.org/browse/COMPASS-6146) to keep track of this issue.

**Comment by AishwaryaChat** [comment]
@Mosallamy  Please let me know if I can work on fixing this issue

**Comment by Mosallamy** [comment]
Hey @AishwaryaChat, please check with one of the maintainers as I'm not working on this project.

**Comment by AishwaryaChat** [comment]
@mcasimir  Please let me know if I can work on fixing this issue

**Comment by mcasimir** [comment]
Hey @AishwaryaChat, sure feel free to submit a PR! please sign our https://www.mongodb.com/legal/contributor-agreement first! Thanks!!

**Comment by AishwaryaChat** [comment]
@Anemy  although I already went through most of the compass code flow, but yes doing the fix requires more discussion with the team. I's not a trait forward fix.
I shall work on https://jira.mongodb.org/browse/COMPASS-6156

**Comment by Anemy** [comment]
Hi @Mosallamy - this is fixed in the newest Compass release `1.34.1` - https://github.com/mongodb-js/compass/releases
Thanks for reporting the issue and helping improve Compass!
