### ISSUE TITLE
Feature Request: Add simplified parallel insertion command syntax

### ISSUE THREAD

**Issue by CodingSpiderFox** [mongodb-js/compass#3630]
## Detailed Description

I want to insert documents into the same logical database in a structured way without unnecessary repetetive typing (syntax is pseudocode only as I will likely mix up Java Lambda expression syntax with JS because I am mainly a Java Engineer)

parallel({
  databases: [
    {dbName: "databaseA", additionalDocuments: []}, 
    {dbName: "databaseB", additionalDocuments: [{"_id": new ObjectId(), "firstname": "additional", "lastName": "additional"]}}, 
    {dbName: "databaseC"}],
  collections: [
    {name: "collectionTest", additionalDocuments: [{"_id": new ObjectId(), "firstName": "coll1", "lastName": "coll2"}]}, 
    {name: "collectionTest2"}}],
  documents: [
  {
      "_id": new ObjectId(),
      "firstName": "hello",
      "lastName": "world"
  },
  {
      "_id": new ObjectId(),
      "firstName": "hello2",
      "lastName": "world2"
  }]
}]

I would expect:
databaseA - collectionTest: [{
      "_id": new ObjectId(),
      "firstName": "hello",
      "lastName": "world"
  },
 {
      "_id": new ObjectId(),
      "firstName": "hello2",
      "lastName": "world2"
  },
{"_id": new ObjectId(), "firstName": "coll1", "lastName": "coll2"}]

databaseA - collectionTest2: [  {
      "_id": new ObjectId(),
      "firstName": "hello",
      "lastName": "world"
  },
  {
      "_id": new ObjectId(),
      "firstName": "hello2",
      "lastName": "world2"
  }]

databaseC - collectionTest: [{
      "_id": new ObjectId(),
      "firstName": "hello",
      "lastName": "world"
  },
 {
      "_id": new ObjectId(),
      "firstName": "hello2",
      "lastName": "world2"
  }]

databaseC - collectionTest2: [  {
      "_id": new ObjectId(),
      "firstName": "hello",
      "lastName": "world"
  },
  {
      "_id": new ObjectId(),
      "firstName": "hello2",
      "lastName": "world2"
  }]

## Context

I want to do as little typing as possible while manually inserting testdata

**Comment by Anemy** [comment]
Hi @CodingSpiderFox - to clarify is this something you'd like exposed in the UI? Where might it live?

As I mentioned in the other issue you created, I'm going to close this issue if that's alright, we've moved our feature requests to the feedback forum as they're easier to track there and we'd like to prioritize bugs and issues on GitHub. You can find the feedback forum here: https://feedback.mongodb.com/forums/924283-compass we also just updated the issue template to reflect this - sorry for the inconvenience.
I don't see anything quite like this on the forum, I think most folks probably end up writing a script for [mongosh](https://www.mongodb.com/docs/mongodb-shell/crud/insert/#std-label-mongosh-insert) for things like that. Internally here at MongoDB we've been discussing a tool that would augment quick data creation for things like seeding a staging database with realistic amounts of documents. Nothing to show yet. There are also some open source tools for that sort of thing out there in the ecosystem.

As a workaround for now I'd recommend using the embedded shell for inserting multiple documents into different places. This is the same video as the other comment but I think it shows how it might be done:

https://user-images.githubusercontent.com/1791149/198316169-817d3789-4bb9-4c09-86a6-ba5b7f6c123d.mp4

**Comment by CodingSpiderFox** [comment]
Thanks, 

seeding the DB with sample documents like persons, addresses etc. would be nice like with the "faker" library
Also, a mongo script would be possible for me, and after thinking about it would be better because with the proposal I made the syntax of mongodb commands might become too bloated. I guess only few people would be willing to learn that for just such a small benefit. I guess the mongosh script would be the better option for them, too.
