### ISSUE TITLE
Bug Report | cannot query using big int

### ISSUE THREAD

**Issue by Lix1993** [mongodb-js/compass#3760]
#### Current Behavior
Insert one doc to collection:
```json
{
  "_id": {
    "$numberLong": "1590276559111561229"
  }
}
```
![image](https://user-images.githubusercontent.com/12579295/201884846-de4f3dc2-8cf8-4eb1-908c-001b77c54335.png)

query by _id get no result
![image](https://user-images.githubusercontent.com/12579295/201884960-5362b199-3dd3-40f5-bc3f-2dcff04f1085.png)

**Comment by Lix1993** [comment]
is this a json issue?

https://github.com/json5/json5/issues/292

**Comment by addaleax** [comment]
Yes, this is a JS/JSON issue. You should be able to use `{ _id: Long(1590276559111561229) }` in your query, maybe that helps? In the future, we will probably also support `{ _id: 1590276559111561229n }` (the JS bigint syntax).
