### ISSUE TITLE
Fatal bug: The brain of your teams hot-key designer 

### ISSUE THREAD

**Issue by josephusmv** [mongodb-js/compass#3973]
## Bug Report

I was writting aggregation using the compass aggr editor, step by step.
At the point of "bug" happens, I have wrote more than ten steps.
But for a reasonable human mistake , I touched ctrl + Q.
Then I just exited the compass, and all steps lost!
I was met this issue once before, but last time I did not edit so many staffes.
I try  hard but did not found anywhere to change this hot key, 
and No where to found any configure like: "confirm on exit".

For a human being, I didn't see any SW with complex edit function has this kind of anti-human desing.
SO I think there is a FATAL bug hiding in the brain of this feature's designer.
Please fix it.

Please keep fatal bug open this issue untill a honest sorry I recieved.

#### Current Behavior
Anti-human

#### Code/Gist
no

#### Expected Behavior/Code
hot key setting or cached agsregation steps

#### Environment
windwos 11

#### Possible Solution
Fire him/her or send him/her to somewhere could fix his brain problem.

#### Version :
1.35.0

**Comment by gribnoysup** [comment]
Thank you for bringing our attention to the issue, we will look into how we can improve that.

At the same time we will not tolerate anyone who is breaking [GitHub community guidelines](https://docs.github.com/en/site-policy/github-terms/github-community-guidelines#maintaining-a-strong-community), in particular being respectful and empathetic to people around you on this platform, so your account will be blocked from this repository and organization
