### ISSUE TITLE
Rant : Using _id ObjectID as direct filter instead of {_id: ObjectID}

### ISSUE THREAD

**Issue by ASH1998** [mongodb-js/compass#4183]
In previous versions : Just using ObjectID searched for all _id in a collection, now we have to specifically define {_id: ObjectID}.
## Question
Why was this change done ? I have been waiting for this feature to come back but you guys are pushing useless beta features but not this feature which was already present. 
Not to mention using regex search on //i, there comes a prompt for i. 

## Additional context
I am not complaining about janky UI, no editor or lack of integration and 1000 more things, I just want this feature back. 
![Screenshot 2023-03-23 155053](https://user-images.githubusercontent.com/23384411/227174196-62b0dc79-e99b-4f16-ba98-ecc026193bbb.jpg)

**Comment by gribnoysup** [comment]
We opened a ticket to track the issue COMPASS-6651
