### ISSUE TITLE
Bug Report Can't delete collection with specific name

### ISSUE THREAD

**Issue by yjn140** [mongodb-js/compass#4198]
I found that mongodb compass can't delete collection with specific name.

I created a collection called `cmccjx_phone_realname_identityno_.._2010`

I think it is the problem of this..

When I want to delete it in the graphical interface, he prompts that the collection is empty

Other manifestations are that in the UI interface, clicking or double-clicking the collection does not respond. command line execution error

```
$ db.cmccjx_phone_realname_identityno_.._2010.drop
```

```
Error: clone(t={}){const r=t.loc||{};return e({loc:new Position("line"in r?r.line:this.loc.line,"column"in r?r.column:...<omitted>...)} could not be cloned.
    at Object.serialize (node:v8:332:7)
    at u (/Applications/MongoDB Compass.app/Contents/Resources/app.asar.unpacked/node_modules/@mongosh/node-runtime-worker-thread/dist/worker-runtime.js:2:1160)
    at postMessage (/Applications/MongoDB Compass.app/Contents/Resources/app.asar.unpacked/node_modules/@mongosh/node-runtime-worker-thread/dist/worker-runtime.js:2:1768)
    at i (/Applications/MongoDB Compass.app/Contents/Resources/app.asar.unpacked/node_modules/@mongosh/node-runtime-worker-thread/dist/worker-runtime.js:1917:2531156)
```

I execute this command to manually delete

```
$ db["cmccjx_phone_realname_identityno_.._2010"].drop()
```

**Comment by alenakhineika** [comment]
Hey, thank you for reporting the issue. Here is the ticket you can use to track the progress on this: [COMPASS-6806](https://jira.mongodb.org/browse/COMPASS-6806)

**Comment by soyjuanmacias** [comment]
Could it be because I have put a dot in the collection name? not good practice

**Comment by alenakhineika** [comment]
This is actually two successive dots that cause that. For collection names, this is ok to have a dot in their names. We will investigate what fails for the two of them.

**Comment by ahmadkhaledCS** [comment]
Hi everyone I noticed that two dots are not allowed as it is validated in this code notice line 3

![Screenshot 2023-06-17 191142](https://github.com/mongodb-js/compass/assets/77671100/cc22ac83-df56-49e4-8fd2-c172f1ef595b)

and notice the error when tiring to view the collection
![image](https://github.com/mongodb-js/compass/assets/77671100/e47e3a88-5511-4a28-a3fd-107601cfacba)

I guess creating a collection with this name should not be allowed in the first place

**Comment by alenakhineika** [comment]
It should be fixed by now. Feel free to reopen if you encounter the issue again.
