### ISSUE TITLE
"ssh2" module in ssh-tunnel package is obsolete, please consider upgrade

### ISSUE THREAD

**Issue by Soulou** [mongodb-js/compass#4203]
Hello,

We've identified that the `ssh2` version used in https://github.com/mongodb-js/compass/blob/3904cf8445c3449f8f87362208a2b0448f57aded/packages/ssh-tunnel/package.json is obsolete.

Version used is 0.8.9 which is more than 3 years old

Last version of the library is 1.11.0.

It has security consequences, SSH servers which are correctly hardened are not compatible anymore with the SSH tunnel feature.

The reason is that all the available ciphers in `ssh2` 0.8.9 are considered obsolete or are triggering a warning in security audit tools, which is a problem.

Would it be possible to upgrade this dependency to solve this?

Thanks a lot.

**Comment by addaleax** [comment]
Updated again in https://github.com/mongodb-js/compass/pull/4326. I think this can be closed.
